### ISSUE TITLE
Are we handling `from_python(bool)` and `is_true(from_python(bool))` correctly?

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1014]
I think right now converting a boolean creates a 0 or 1 integer. Is this want we want to do? 

Ideally  for a boolean _x_ `from_bool(x).is_true() == x` 

WL does have True and False

**Comment by rocky** [comment]
There is a broader point that I've been meaning to mention ever since on one of the google groups we glibly suggested that one would be able magically run `to_python()`, `from_python()`, or `to_sympy()` and magically that would work. 

When I look at the existing types of conversions, things are a bit lacking and probalby there is an easy set of things to do to make this work better. Working though specific examples (such as trying to do this in mathicsscript for example) has and probalby will get us closer to supporting the easy stuff, and will probably give us a better understanding of how to guide others to use Mathics as a Python library. (This was one of our bullet points in the Sage-Day demo).

However I know that to do a good job in any of these functions would take a signifcant amount of work, and a significant amount of explaining the subtleties.

The good news is that we've started on this journey, and I think the journey is worth it.

 The bad news is that it is still a long journey.

**Comment by mmatera** [comment]
Let's start fixing it with PR #1020

**Comment by rocky** [comment]
Fixed by #1020. 

The broader issue of handling to_python() remains a research project and probably not something to track in a issue without breaking this up into small pieces like this one (handle boolean) .

Of course adding more tests and round-trip tests is a worthwhile endeaver too, but that's also probably a separate issue.
