### ISSUE TITLE
Add -no-prompt option to mathics command-line

### ISSUE THREAD

**Issue by jbigtower** [mathics/Mathics#102]
How we can use mathics in command line like other programs? In a server it is important to use mathics in the form
mathics < input.m > output.txt
and this does not work.

It seems that this is a python problem with the input/output files.

With some upgrade, changing the main.py file, in this page it works
mathics < input.m
in this case the output appear in the screen, but it is impossible to save the output in a file.

Can anyone help me?

Thanks,

**Comment by rocky** [comment]
[`mathicsscript` ](https://github.com/mathics3/mathicsscript) now has `--no-prompt`. Note the double dashes at the front though.
