### ISSUE TITLE
Is it possible to add auto-complete?

### ISSUE THREAD

**Issue by wuyudi** [mathics/Mathics#1050]
There is no auto-complete now, so it's kind of hard to input function names.

**Comment by rocky** [comment]
If you mean inside the command-line utility, there is function name completion in [mathicsscript](https://github.com/Mathics3/mathicsscript).

If you mean for Django, web interface the long-term plan is to use some sort of Jupyter-based front-end. 

Lastly, I'll mention that this project has been short of help. So if this is something you want to work on, please do.

**Comment by rocky** [comment]
@wuyudi you seem  to ask vague questions and then are being unresponsive when help is offered and information is needed.
