### ISSUE TITLE
Implement TimeConstrained

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1059]
See https://reference.wolfram.com/language/ref/TimeConstrained.html

This is needed in Rubi.

**Comment by mmatera** [comment]
If this can wait until the next week, I can handle it

**Comment by rocky** [comment]
This can wait until next week and you can handle it. 

I was going to add that there are basically two approaches for this. One is to set an "alarm" signal and use a signal handler to handle that. See [this](https://code-maven.com/python-timeout) for an example of that. 

The other way, and I think this is better, is a combination of the multiprocessing library and threads. See https://medium.com/@chaoren/how-to-timeout-in-python-726002bf2291

Of course, you might come up with a 3rd or 4th way. Implementer's choice!

**Comment by mmatera** [comment]
I just used the routine `run_with_timeout_and_stack` that is already implemented in core/evaluation.py

**Comment by rocky** [comment]
Ok - that makes sense. It seems use use the timeout alarm. 

In the future if we want to multithread operations, we will need to keep in mind this subtle fact.

Hmm.... maybe we should make note of that now....

Do you mind if I run black on the PR?

**Comment by mmatera** [comment]
No problem, go ahead...
