### ISSUE TITLE
Text (in Graphics) is broken

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1078]
To see brokenness run:

```
Graphics[{Circle[], Text["a"]}]
```

Compare that without adding `Text["a"]`:

```
Graphics[{Circle[]}]
```

This was noticed a while ago and I think @poke1024 started addressing this in PR #635 or at least the [PDF](https://github.com/mathics/Mathics/files/464285/Transforms.pdf) from an earlier PR #486 show this working.

**Comment by mmatera** [comment]
#1145 would fix this issue.
