### ISSUE TITLE
Could not install mathics using git

### ISSUE THREAD

**Issue by zhogano** [mathics/Mathics#1097]
I tried to install mathics from git with the following command. There was no errors. However when I tried to run by typing `mathics` it gave errors.  I am not a developer, so I couldn't understand it. `pip install Mathics3` also didn't work for me. Any help would be appreciated. (Well actually I had installed it before and it broke after recent update on Linux/ python. Now I am unable to fix it.)

```
$ git clone https://github.com/mathics/Mathics.git
$ cd Mathics
$ sudo make install

$ cd ..
$ git clone https://github.com/Mathics3/mathics-django.git
$ cd mathics3-django
$ sudo make install

$ cd ..
$ git clone https://github.com/Mathics3/mathicsscript.git
$ cd mathicsscript
$ sudo make install
```

Output when I type `mathics` to start the program: (typing `mathicsscript` results in similar output)

```
Traceback (most recent call last):
  File "/usr/bin/mathics", line 33, in <module>
    sys.exit(load_entry_point('Mathics3==2.0.0.dev0', 'console_scripts', 'mathics')())
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/main.py", line 278, in main
    definitions = Definitions(add_builtin=True, extension_modules=extension_modules)
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/core/definitions.py", line 70, in __init__
    from mathics.builtin import modules, contribute
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/builtin/__init__.py", line 5, in <module>
    from mathics.builtin import (
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/builtin/plot.py", line 32, in <module>
    from mathics.builtin.compile import _compile, CompileArg, CompileError, real_type
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/builtin/compile/__init__.py", line 13, in <module>
    from .compile import _compile
  File "/usr/lib/python3.9/site-packages/Mathics3-2.0.0.dev0-py3.9-linux-x86_64.egg/mathics/builtin/compile/compile.py", line 2, in <module>
    import llvmlite.binding as llvm
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so
```

**Comment by suhr** [comment]
You need to install llvmlite.

**Comment by rocky** [comment]
Also look at https://mathics-development-guide.readthedocs.io/en/latest/installing.html#os-dependent-packages

**Comment by zhogano** [comment]
Thank you for your answers.

to install llvmlite, I gave the following command: 
`pip install llvmlite`
Output is:
```
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: llvmlite in /usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg (0.35.0)
```
I also installed other python-dev by:
`pip install python-dev`

python-setuptools 1:51.0.0-1 is already installed on my system.

I still get the same output after `mathics`

**Comment by GarkGarcia** [comment]
> OSError: Could not load shared object file: libllvmlite.so

This is an issue we were facing in CI a while ago. It turns out installing `llvmlite` from PyPI isn't enough: you need to install the LLVM library from your system's package-manager so that `llvmlite` can hook into it. You need LLVM version >= 10, which may not be the default `llvm-dev` package in some LTS distros. To install LLVM 10 in Ubuntu or Debian-based distros please run `$ sudo apt install llvm-10-dev`.

**Comment by GarkGarcia** [comment]
To verify that this is an issue with your LLVM installation you can try to run the following:

```
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite
```

You should see an error similar to the one you described.

**Comment by zhogano** [comment]
@GarkGarcia, I tried it but there was no error. And it was just waiting for a new input:
```
python3
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite
>>> 
```
To install LLVM 10 I ran `sudo pacman -S llvm10`, because my distro is arch-linux based Manjaro. There was no `llvm-10-dev`. 
The output is:
```
resolving dependencies...
looking for conflicting packages...

Packages (1) llvm10-10.0.1-3

Total Installed Size:  230.00 MiB

:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                     [######################] 100%
(1/1) checking package integrity                   [######################] 100%
(1/1) loading package files                        [######################] 100%
(1/1) checking for file conflicts                  [######################] 100%
(1/1) checking available disk space                [######################] 100%
:: Processing package changes...
(1/1) installing llvm10                            [######################] 100%
Optional dependencies for llvm10
    python-setuptools: for using lit (LLVM Integrated Tester) [installed]
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

Then I tried `sudo pip install Mathics3` and afterwards `sudo pip install mathicsscript`. The output is attached. Afterwards when typing `mathics` or `mathicsscript` I still get the same error.

Then I tried to install mathics from AUR. When installing dependencies it gave an error and aborted installing.


[mathics_pip_install.txt](https://github.com/mathics/Mathics/files/5769877/mathics_pip_install.txt)


![mathics_aur_error](https://user-images.githubusercontent.com/65014018/103641497-c0c0cd80-4f49-11eb-83c3-c764363bd492.png)

What I wonder is that Mathics was working on my computer before the major upgrade on my linux packages and python.  Then it broke down and I couldn't fix it. Maybe on next upgrade things will be fixed up on my computer, because the upgrade introduced some other minor problems too.





> To verify that this is an issue with your LLVM installation you can try to run the following:
> 
> ```
> $ python3
> Python 3.6.9 (default, Oct  8 2020, 12:12:24)
> [GCC 8.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import llvmlite
> ```
> 
> You should see an error similar to the one you described.

**Comment by GarkGarcia** [comment]
> What I wonder is that Mathics was working on my computer before the major upgrade on my linux packages and python.

What was the update about? Could you provide some more details? What were the packages updated? Did you remove any packages from your system after the update (because it was considered as "autoremovable" by pacman)?

**Comment by zhogano** [comment]
> Ok, try running the following and tell me what the output is:
> 
> ```
> $ python3
> >>> import llvmlite.binding as llvm
> >>> llvm
> ```

The output is:
```
python3
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llvmlite.binding as llvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/ffi.py", line 153, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: libllvmlite.so
>>> llvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'llvm' is not defined
>>> 
```

**Comment by zhogano** [comment]
> > What I wonder is that Mathics was working on my computer before the major upgrade on my linux packages and python.
> 
> What was the update about? Could you provide some more details? What were the packages updated? Did you remove any packages from your system after the update (because it was considered as "autoremovable" by pacman)?

Almost everything including python was updated (too many packages, ~3.7 gib in total). I don't remember removing any specific packages that can be related to Mathics (I removed KDE plasma related packages but that was after I realized Mathics was not working) . There is a time gap between the last run of Mathics and the upgrade. The reason can be something else before the upgrade, but the upgrade seems more probable to me.

**Comment by GarkGarcia** [comment]
> The output is:
> 
> ```
> python3
> Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
> [GCC 10.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import llvmlite.binding as llvm
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/__init__.py", line 4, in <module>
>     from .dylib import *
>   File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/dylib.py", line 3, in <module>
>     from llvmlite.binding import ffi
>   File "/usr/lib/python3.9/site-packages/llvmlite-0.35.0-py3.9.egg/llvmlite/binding/ffi.py", line 153, in <module>
>     raise OSError("Could not load shared object file: {}".format(_lib_name))
> OSError: Could not load shared object file: libllvmlite.so
> >>> llvm
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'llvm' is not defined
> >>> 
> ```

Ok, this shows us that there is a problem with you LLVM installation. Try installing [`llvm-libs`](https://archlinux.org/packages/extra/x86_64/llvm-libs/) then run the same test again.

> Almost everything including python was updated (too many packages, ~3.7 gib in total). I don't remember removing any specific packages that can be related to Mathics (I removed KDE plasma related packages but that was after I realized Mathics was not working) . There is a time gap between the last run of Mathics and the upgrade. The reason can be something else before the upgrade, but the upgrade seems more probable to me.

The more precise you are the more we can help. I suspect the update uninstalled `llvm-libs` because it marked it as "autoremovable". Since you haven't installed Mathics from the AUR or the Arch repositories, `llvm-libs` wasn't marked as a dependency, so `pacman` had no reason to keep it installed in your machine. By explicitly installing `llvm-libs` the package will be marked as "explicitly installed" and will not be removed automatically in the future.

**Comment by GarkGarcia** [comment]
> The more precise you are the more we can help. I suspect the update uninstalled `llvm-libs` because it marked it as "autoremovable". Since you haven't installed Mathics from the AUR or the Arch repositories, `llvm-libs` wasn't marked as a dependency, so `pacman` had no reason to keep it installed in your machine. By explicitly installing `llvm-libs` the package will be marked as "explicitly installed" and will not be removed automatically in the future.

I could be wrong here, maybe that's not the issue. But there's definitively a problem with your LLVM installation.

**Comment by zhogano** [comment]
> The more precise you are the more we can help. I suspect the update uninstalled `llvm-libs` because it marked it as "autoremovable". Since you haven't installed Mathics from the AUR or the Arch repositories, `llvm-libs` wasn't marked as a dependency, so `pacman` had no reason to keep it installed in your machine. By explicitly installing `llvm-libs` the package will be marked as "explicitly installed" and will not be removed automatically in the future.

`llvm-libs` was already installed. However, I downloaded `llvm-libs`from the link you have given and installed it, which is version 11.0.1-1 [extra].  Before that it was 11.0.1-0. But nothing changed. Today I realized that `snap` is also broken on my computer. `snap` packages don't work anymore. Maybe it is related with kernel, because I recently updated it to 5.10.2-2, but then switched back to 5.4.85-1 because it is LTS recommended version. Next time I will boot with kernel 5.10.2-2 and try again.

**Comment by rocky** [comment]
Assuming this is addressed. If not, please narrow the problem.
