### ISSUE TITLE
 No module named 'mathics_django.server'

### ISSUE THREAD

**Issue by ouening** [mathics/Mathics#1110]
I have encountered an error as the title said. Can someone tell me how to fix it?
![image](https://user-images.githubusercontent.com/15122811/104536832-c908bf00-5653-11eb-89ce-ac15a8d3f63a.png)

**Comment by bplcn** [comment]
I encountered the same problem when starting the maticsserver on Win10 OS. Python version is 3.8.5

**Comment by kxxt** [comment]
I encountered the same problem both on Windows 10 with python 3.8 and on wsl ubuntu.

**Comment by kxxt** [comment]
Maybe this issue should be moved to [mathics-django](https://github.com/Mathics3/mathics-django)?

**Comment by GarkGarcia** [comment]
> Maybe this issue should be moved to [mathics-django](https://github.com/Mathics3/mathics-django)?

Yes, thanks for that!

**Comment by GarkGarcia** [comment]
See https://github.com/Mathics3/mathics-django/issues/10 for further discussion.
