### ISSUE TITLE
Can't import mathematica notebooks.

### ISSUE THREAD

**Issue by rog77** [mathics/Mathics#1184]
I'm a new user, with a fresh install, running mathicsserver - I can connect to the local server and see the default page, but I can't work out how to import a mathematica notebook (*.nb) file, any help or useful links would be much appreciated. Thanks!

**Comment by mmatera** [comment]
We do not have this yet. What you can do is to convert your notebook to a   `.m` package from the Notebook interface of WMA, and then load that .m in mathics. In the future, we have plans to implement some kind of importer to a notebook format (let's say, jupyter)

**Comment by rog77** [comment]
Thanks for the info!
