### ISSUE TITLE
Read[StringToStream["..."], Hold[Expression]]

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1234]
Split off from #1174

* https://github.com/mathics/Mathics/issues/1174#issuecomment-806073268
* https://github.com/mathics/Mathics/issues/1174#issuecomment-806604428

@mmatera is this something you are going to handle? If not, let me know and I will look at it.

This seems to be the next main obsticle in getting #1174 working.

**Comment by mmatera** [comment]
I am trying to fix the issue with the ``Derivative``s.  If you want, go ahead!

**Comment by vsht** [comment]
Let me know once you have branch I can test my codes against.

**Comment by mmatera** [comment]
Addressed by #1242.

**Comment by rocky** [comment]
Think this is addressed. If not reopen with comments.
