### ISSUE TITLE
$InputFileName stopped working

### ISSUE THREAD

**Issue by vsht** [mathics/Mathics#1300]
This used to work few weeks ago
```
(*getme.m*)
Print[$InputFileName];
```

```
In[1]:= Get["getme.m"]                                                                                                                       
/home/vs/Downloads/getme.m
```

but now I get only an empty string.

[getme.zip](https://github.com/mathics/Mathics/files/6360164/getme.zip)

**Comment by rocky** [comment]
I probably broke this in doing https://github.com/mathics/Mathics/pull/1281 . I'll take a look when I get a chance. 

I also thing `ReadList[]` is broken too, but I think this had been broken for a while and I just changed the brokenness.

**Comment by rocky** [comment]
I can confirm that in b17962828423e8b10489de03b9206515bd476e5b the commit before I started the refactor this works.


And this is probably and easy fix too, just need some time to be able to address this though.

**Comment by rocky** [comment]
@vsht https://github.com/mathics/Mathics/pull/1304 add the two lines that got inadvertently dropped. However for this to be complete, I should add tests so this kind of thing doesn't happen again.

**Comment by rocky** [comment]
Buy https://github.com/mathics/Mathics/pull/1325 this has been more fully addressed. 

If not, feel free to reopen.
