### ISSUE TITLE
how do you run this from a python script?

### ISSUE THREAD

**Issue by Kreijstal** [mathics/Mathics#1422]
I know you usually want this to execute this from the shell, but is it possible to call mathics functions from python?

**Comment by rocky** [comment]
Does https://mathics-development-guide.readthedocs.io/en/latest/extending/developing-code/calling-mathics-library-from-within-python-code.html#using-mathicssession  answer your question? 

If not, loot at other parts of the document. And if you still have questions, I think we'd need more detail and context about what it is you want to do.

**Comment by Kreijstal** [comment]
Yes, it does. I didn't find this easily.
