### ISSUE TITLE
requirements-full.txt not included in released source code

### ISSUE THREAD

**Issue by vicp74** [mathics/Mathics#1452]
There's a [similar issue as in mathics-scanner](https://github.com/Mathics3/mathics-scanner/issues/29): requirements-full.txt is not present in the released [Mathics3-3.0.0.tar.gz](https://github.com/mathics/Mathics/releases/download/3.0.0/Mathics3-3.0.0.tar.gz), but in this case it is present in [Source code (zip or tar.gz)](https://github.com/mathics/Mathics/archive/refs/tags/3.0.0.tar.gz). Can it also be included in the first one?

**Comment by rocky** [comment]
Should be there now  in mathics-scanner 1.2.3.

**Comment by vicp74** [comment]
I mean the problem is **also** present in Mathics. Please reread my previous message without taking into account mathics-scanner.

**Comment by rocky** [comment]
Ok - thanks for the clarification. Next week I'll try to release another Mathics version.

**Comment by rocky** [comment]
@vicp74 @thierry-FreeBSD --- I think in the last release this is now fixed.

**Comment by vicp74** [comment]
Yes, it's fixed. Thanks!
This issue can be closed now.
