### ISSUE TITLE
Quantile[Range[16], 1/4] wrong result?

### ISSUE THREAD

**Issue by axkr** [mathics/Mathics#1540]
Example in Quantile doc:

```
Quantile[Range[16], 1/4]
```

returns `5`  should be `4` in Docker container.

**Comment by rocky** [comment]
This is hand-hacked code. I'd like to replace it with numpy's or scipy's version. However for numpy

```
import numpy
>>> numpy.quantile(range(1, 16), 1/4)
4.5
```

**Comment by rocky** [comment]
The Details section in https://reference.wolfram.com/language/ref/Quantile.html provides details and rules for how to do.
