### ISSUE TITLE
Add `AssociateTo`

### ISSUE THREAD

**Issue by TiagoCavalcante** [mathics/Mathics#1545]
https://reference.wolfram.com/language/ref/AssociateTo.html

**Comment by rocky** [comment]
I started looking at this and it is not too difficult. However it brings up what I think is a weakness we currently have with associations: they aren't stored in any sort of efficient or Python-friendly way, but instead are S-expressions.

And this makes things like `AssociateTo` a little more cumbersome. 

So instead what I am thinking of now is taking a longer view and adding a Python dictionary representation that is most useful here, but also useful in the other operations.  

And by its nature suggests adding `to_python()` and `from_python()` routines which would also be desirable.

**Comment by TiagoCavalcante** [comment]
This already was added.
