### ISSUE TITLE
"manage.py runserver" gives "Interruptingcow can only be used from the MainThread"

### ISSUE THREAD

**Issue by bnjones** [mathics/Mathics#158]
Steps to reproduce:

* Install with `setup.py develop`
* Run `python mathics/manage.py runserver` inside the source tree
* Go to http://localhost:8000/

I get a Django exception page when I do this.

I guess this means that `manage.py runserver` runs the Django app in a separate thread. It looks like this check exists because interruptingcow uses `alarm()` and a signal handler for `SIGALRM` to implement its timeouts, and the [Python docs](http://docs.python.org/2/library/signal.html) say that signal handlers can only be set from the main thread.

I'm not sure if this is important enough to be worth fixing - I don't have any ideas about what the fix might be, but I thought it was worth raising it in case it turns out to be important.

**Comment by sn6uv** [comment]
I hit this issue setting up a Mathics mirror on my VPS. The workaround I found was to disable the evaluation timeout, i.e. `TIMEOUT = None` in settings.py. This is obviously not ideal.

**Comment by sn6uv** [comment]
Interrupting cow is no longer maintained. I've coded up a replacement that also uses signals (so it's unlikely to fix this). Django does have it's own signals module, but I'm yet to investigate it.

**Comment by sn6uv** [comment]
I found quite a few people with similar issues to this. Of note is [this stackoverflow entry](https://stackoverflow.com/questions/8572830/pythondjango-signal-handler-and-main-thread) which suggests:

`python manage.py runserver --noreload --nothreading`

**Comment by sn6uv** [comment]
Fixed by #323
