### ISSUE TITLE
Beef up pytest to allow for a benchmarking option

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#1581]
We can  enhance the pytests to facilitate benchmarking the tests. 

While it is true that benchmarking and testing are separate, a simple change here can give some idea.

Basically most of the pytests funnel through a few  helper routines. So that would test an environment setting and accumulate timings if that's set.

**Comment by TiagoCavalcante** [comment]
@rocky I think it is already fixed by `TraceBuiltins`.

**Comment by rocky** [comment]
Yes, benchmarking in another repo is much better here.
