### ISSUE TITLE
Consider using Github's "rename repo" and "transfer repo" feature

### ISSUE THREAD

**Issue by Techcable** [mathics/Mathics#1586]
If you use Github's [trasnsfer repo](https://docs.github.com/en/github-ae@latest/repositories/creating-and-managing-repositories/transferring-a-repository) feature it would automatically update every link.

I've used it several times and it works great.

Just adding this in case you might have missed it :smile:

**Comment by rocky** [comment]
Wasn't aware of it - thanks for pointing it out!

**Comment by rocky** [comment]
Closing because for now we are keeping this repository, not transfering or renaming it. 

And the other repository has things adjusted.
