### ISSUE TITLE
ModuleNotFoundError: No module named 'mathics_scanner'

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#1589]
On Slackware64 15.0 up-to-date stable, mathics crashes.
I installed numpy, sympy, wheel (for pip2tgz,) pip2tgz, did 'pip2tgz Mathics3-4.0.0.tar.gz' to build package to see if I can get this working for a SlackBuild (for SlackBuilds.org.)  Here's a short log.  It maybe was a pip2tgz issue but I'm unsure will be able to create package w/only pip because must--as root--install to specific directory then package will be built from.

```
root@0.vanaheim:~# mathics
Traceback (most recent call last):
  File "/usr/bin/mathics", line 5, in <module>
    from mathics.main import main
  File "/usr/lib64/python3.9/site-packages/mathics/main.py", line 12, in <module>
    from mathics.core.parser import MathicsFileLineFeeder, MathicsLineFeeder
  File "/usr/lib64/python3.9/site-packages/mathics/core/parser/__init__.py", line 3, in <module>
    from mathics_scanner import is_symbol_name
ModuleNotFoundError: No module named 'mathics_scanner'
```

**Comment by rocky** [comment]
See https://mathics-development-guide.readthedocs.io/en/latest/installing/index.html#installing-mathics

Also, active work on Mathics core is now done at https://github.com/mathics3/mathics-core  This is mentioned in the "about" for this project.

**Comment by dchmelik** [comment]
Yeah, I shouldn't have used pip2tgz yet; mathics works fine on Slackware64 15 if I just did 'pip3 install Mathics3.'
