### ISSUE TITLE
mathics crashes because of failing importing numpy C-extensions (openblas?)

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#1590]
On Slackware64 15.1+current mathics crashes ([gist](https://gist.github.com/dchmelik/4459bd5f8177225b2991dad77b57cac7)) because fails import numpy C-extensions (openblas?)  This is also after I built package 'pip2tgz Mathics3-4.0.0.tar.gz' but earlier used only from pip and think I saw same (but can retest.)

**Comment by rocky** [comment]
Looks to me that you don't have a functioning numpy.
