### ISSUE TITLE
Dividing Expansions does not work

### ISSUE THREAD

**Issue by Arsalan-Zahid** [mathics/Mathics#1593]
Hello there,

it seems that dividing expansions does not work in Mathics.

`Clear["Global`*"]

"Cos Expansion"
CosExpansion=Series[Cos[x], {x, Pi/4, 4}]

"E Expansion"
EExpansion=Series[E^x,{x,Pi/4,4}]

"Divided after expanding (EExpansion /CosExpansion)"
EExpansion / CosExpansion`

gets a very long error which is about 370k characters long, so I can't post it here.

**Comment by rocky** [comment]
Hi. Looks like we are getting an infinite expansion. 

Nowadays all of the development is done in https://github.com/Mathics3/mathics-core. If you copy this issue over to the issue tracker there, I'll post more information.

**Comment by rocky** [comment]
Works over in Mathics3. If there is something more, continue the discussion there.
