### ISSUE TITLE
Span does not behave correctly

### ISSUE THREAD

**Issue by davidmashburn** [mathics/Mathics#196]
Span seems to be misbehaving for me...

The most egregious example I can find is the standard reverse operation:
{1,2,3,4,5}[;; ;;-1]

This should obviously give:
{5,4,3,2,1}

As a starting point, you might want to look at something like "genericSlice" from my np_utils project. It builds slices, but with 3 additional options (includeStop, oneBased, and checkBounds):

https://github.com/davidmashburn/np_utils/blob/master/np_utils/list_utils.py

I also made a gist with just the function with a simple test case:
https://gist.github.com/davidmashburn/9764309

I know Python's indexing is: includeStop=False, oneBased=False, checkBounds=False.
Matlab and Octave would be: includeStop=True, oneBased=True, checkBounds=True.
I think Mathematica should be as well, but you may have to double-check me...
Indexing can get tricky...

If that turns out to be right, you could simply the function by hard-coding those values to eliminate some options.

Cheers,
-David

**Comment by wolfv** [comment]
I think this behaviour is correct, yes.

Additionally this case should be covered:

`{1,2,3,4}[[3;;1]]`
= Not possible (3 > 1)

`{1,2,3,4}[[1;;3;;-1]]`
= Not possible (-1 > -3)

**Comment by wolfv** [comment]
Also, this is a big bug:

`{1,2,3,4,5}[[3;;1;;=1]]`
` = {3}`

Should be:

`{1,2,3,4,5}[[3;;1;;-1]]`
` = {3,2,1}`
