### ISSUE TITLE
online server --- 502 Bad Gateway 

### ISSUE THREAD

**Issue by FredLunnon** [mathics/Mathics#201]
Attempts to access http://www.mathics.net/ result in error message 
"502 Bad Gateway". 

This issue has been reported by several users elsewhere on the internet 
during the past fortnight. 

My configuration comprises recent iMac 27" running Mavericks and Firefox. 

WFL

**Comment by mailmindlin** [comment]
Just checked, the site is still down

**Comment by ahalekelly** [comment]
Mathics.net is still down.

**Comment by rashivkp** [comment]
now its up, but for every instruction it return 500 error. may be don't have access to db.

**Comment by sn6uv** [comment]
I'm running a mirror on http://angusgriffith.com:8000/ that people can use when mathics.net is down. It's not as powerful as the main server but it's got a more up to date version of Mathics.

**Comment by FredLunnon** [comment]
"cannot connect to server"
   http://angusgriffith.com:8000/

WFL

**Comment by sn6uv** [comment]
@FredLunnon, that's the old url. See my edit as of a couple days ago. mathics.angusgriffith.com

**Comment by FredLunnon** [comment]
Running in Firefox under Mavericks on iMac at
    http://www.mathics.net/
Site responds.  However nothing will execute: eg.

    Binomial[5, 3]
        Sorry, an error occurred while processing your request!

WFL

**Comment by sn6uv** [comment]
@FredLunnon did you try http://mathics.angusgriffith.com/ ?

**Comment by FredLunnon** [comment]
http://mathics.angusgriffith.com/

successfully executes

    Binomial[5, 3]
        10
    Binomial[-5, -7]
        0

[ And it gets the answer right, better than Mathematica can manage at

    http://www.wolframalpha.com ]

    Simplify[(Binomial[n-1, k-1] + Binomial[n-1, k] - Binomial[n, k])]
        0

This works also, but requires use of Simplify[ ], unlike WolfA.

  This site would surely be of interest to mathematical colleagues:
would you object to my publicising it on the math-fun list?

WFL

**Comment by FredLunnon** [comment]
Alas, the more ambitious

    Plot3D[Abs[-Sqrt[(z/(-1 + z))] EllipticK[1/(1 - z)] +
        EllipticK[1/z]] /. z -> x + I*y, {x, -1, 2}, {y, -1, 1},
      PlotRange -> All, AxesLabel -> Automatic]

produced only the usual (dispiritingly generic) error message,
then crashed your server:

    504 Gateway Time-out

WFL

**Comment by sn6uv** [comment]
Yes, the server it's running on isn't very powerful and can get stuck doing long calculations like plotting. It's will come back alive after some time (it's back now).
If you want to experiment with the computationally difficult features you might be better off running your own Mathics server, see https://github.com/mathics/Mathics/wiki/installing

Definitely not, getting more publicity would be great!
