### ISSUE TITLE
loss of precision when computing the gamma function

### ISSUE THREAD

**Issue by Carlos-Coelho** [mathics/Mathics#203]
When trying to compute the Gamma function with extended precision it seems that the values obtained are only correct till 16-18 decimal places, indeed the command

N[N[Gamma[24/10],100]/N[Gamma[14/10],100],100]

gives the result

1.4000000000000000000867361737988403547205962240695953369140625

**Comment by sn6uv** [comment]
It looks like a  bug in `Gamma` (with `N`) itself:
```mathematica
In[1]:= N[Gamma[2], 100]
Out[1]= 1.

In[2]:= % // Precision
Out[2]= 18.
```
