### ISSUE TITLE
Integrate[...] prints unicode F74C instead of "d" in "dx"

### ISSUE THREAD

**Issue by ghost** [mathics/Mathics#206]
I can reproduce this by opening http://www.mathics.net/ and doing:

```
Integrate[y[x], x]
```

which gives:

```
 ∫y[x]x
```

**Comment by limeblack** [comment]
@bnjones @vcatt I disagree with bnjones.  This breaks coping and pasting with Mathematica, so I think this shouldn't be changed.

Is there a way to link to a remote font or maybe automatically request to install it on the OS?

**Comment by GarkGarcia** [comment]
> Is there a way to link to a remote font or maybe automatically request to install it on the OS?

Kind of. We could include the fonts in the repository. That way it's copied locally on install.

**Comment by GarkGarcia** [comment]
See https://github.com/Mathics3/mathics-django/issues/4 for updates.
