### ISSUE TITLE
Syntax error for correct complex expression with several occurrances of Sqrt

### ISSUE THREAD

**Issue by preitinger** [mathics/Mathics#211]
The following expression cannot be interpreted. Btw it was the output of a previous calculation also with Mathics...

Sqrt[(r+(−py*r^2+Sqrt[px^2*r^2*(px^2+py^2-r^2)])/(px^2+py^2))*(r+(py*r^2-Sqrt[px^2*r^2*(px^2+py^2-r^2)])/(px^2+py^2))]

**Comment by sn6uv** [comment]
Closing this as I am unable to reproduce the incorrect output. Feel free to reopen this if you remember what that command was.
