### ISSUE TITLE
`Import` function and data JSON/XML handling

### ISSUE THREAD

**Issue by errordeveloper** [mathics/Mathics#22]
It would be very interesting to be able to use `Import[]` in Mathics with support for getting data from an HTTP API as XML and/or JSON.

I'd be happy to start hacking on this as it shouldn't be difficult to just use an existing Python library which fetch a URL, though the Mathics internals is something I currently have no idea about.

**Comment by rocky** [comment]
@mmatera This is done, right?

**Comment by mmatera** [comment]
Not sure. But this is too old. Maybe we can face this again in the future.
