### ISSUE TITLE
DSolve fails, apparently due to wrong answer from Ingegration

### ISSUE THREAD

**Issue by wujzboj** [mathics/Mathics#228]
DSolve[y'[t] + (a + 2/(3 t)) y[t] == 2 / (3 t), y[t], t] returns the same solution as DSolve[y'[t] + (a + 2/(3 t)) y[t] == 0, y[t], t], apparently because it thinks that Integrate[Exp[-t] t^(-1/3), t] is 0...

**Comment by sn6uv** [comment]
It appears that this issue has been fixed by upgrading Sympy

```mathematica
In[1]:= DSolve[y'[t] + (a + 2/(3 t)) y[t] == 2 / (3 t), y[t], t]
Out[1]= {{y[t] -> (4 E ^ ((-2 I / 3) Pi) (-1 / 3)! lowergamma[2 / 3, a t exp_polar[I Pi]] / (9 a ^ (2 / 3) (2 / 3)!) + C[1]) E ^ (-a t) / t ^ (2 / 3)}}
```
