### ISSUE TITLE
version of sympy is outdated

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#234]
Mathics 0.7 supports `sympy==0.7.3`, but the current version of Sympy is 0.7.6 which is does not work properly (see the [travis test failures](https://travis-ci.org/mathics/Mathics/builds/42960458))

**Comment by dchmelik** [comment]
Should that really be '==' instead of '>=', anyway? I changed the setup.py to say 0.7.5 (from its main SlackBuild) for my SlackBuild, and (after dealing with setting up the other dependencies) Mathics ran fine.

**Comment by sn6uv** [comment]
For the most part it runs fine. If you run the full test suite however (with `python2 mathics/test.py`) there are some crashes due to backwards incompatible Sympy changes
