### ISSUE TITLE
ZIP archive file compiling & running issues (Python omission and errors)

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#239]
Version 0.6.0rc1 zip says run setup.py but does not have it. I made a 0.7rc1 SlackBuild from your source a few minutes ago, but for me (or maybe someone who knows more Python) to release it so people can install Mathics on any Slackware-based system more easily (even automated installation if SlackBuilds,org accepts it), there needs to be a numbered version for which the instructions are correct. I could find no relevant information on python-dev or libgmp3-dev, but I suspect Slackware has equivalents, but I am not sure (or this is for some other reason): when I try to run mathicsserver and mathics, I get the following errors.

    Traceback (most recent call last):
      File "/usr/bin/mathicsserver", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2880, in <module>
        working_set = WorkingSet._build_master()
      File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 432, in _build_master
        ws.require(__requires__)
      File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 741, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 626, in resolve
        raise DistributionNotFound(req)

**Comment by sn6uv** [comment]
You could use the tar.gz file instead of zip (see the releases on github). I'm not familiar with slackwares packaging procedures. The zip file was mostly intended for Windows users

**Comment by dchmelik** [comment]
I cannot find the .tar.gz... could someone add a link or several to it, preferably also on the main page and in as many of the various instructions (pages, included files) as possible?

**Comment by bnjones** [comment]
You can find all the release tarballs and zip files at https://github.com/mathics/Mathics/releases (or click the "N releases" link at the top of the main project page. I agree this isn't very easy to find, maybe adding a link to `README.rst` would help.
