### ISSUE TITLE
bug running 0.6.0rc1

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#240]
I made a SlackBuild for 0.6.0rc1, and I think Slackware has equivalents of the dependencies for Mathics but am not sure. I get the following error.

Traceback (most recent call last):
  File "/usr/bin/mathicsserver", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: interruptingcow

**Comment by dchmelik** [comment]
I have been informed Slackware does not have separate 'dev' packages (the sort of thing you should consider when writing your installation instructions, rather than assuming everyone is running some very specific newer distribution with packages that have not been called 'linuxpackages' as a standard type, i.e. historically at linuxpackages.net or something), and Slackware has version three of everything, except version 5 of GMP, so theoretically Mathics should work on it unless GMP is not backwards compatible and you are using an old version.

**Comment by dchmelik** [comment]
Actually, someone told me Slackware has Python 3, but they were wrong--it is 2.7. I can download 3 and retry. You may as well delete this bug for now (I do not know how).

**Comment by dchmelik** [comment]
Ok, I forgot you do not need Python3, so I switched back, and someone told me the problem was in pysetuptools, which I installed/upgraded. Then I get a longer error, below.

Traceback (most recent call last):
  File "/usr/bin/mathics", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 2880, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 432, in _build_master
    ws.require(__requires__)
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 741, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib64/python2.7/site-packages/pkg_resources.py", line 626, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: interruptingcow

**Comment by dchmelik** [comment]
I still got an error and was talking to people on my OS IRC channel, and the Python one, and found out that you actually have several undocumented dependencies, that may be on your distribution, but not others. These include interruptingcow, colorama, argparse, but I will have to find and build/install argparse, next, to see if Mathics will work or if it will crash with another dependency called after argparse. It would be great if you could do some research on this and complete your true list of dependencies.

**Comment by sn6uv** [comment]
Yes, we depend on those too. The full list is given in `setup.py`.

**Comment by dchmelik** [comment]
Actually, the argparse thing was a well-known error with Python 2.7 itself that affects lots of dependent software, and because of that, you should probably not have argparse in setup.py--at least on Slackware, and Redhat if I recall, and most likely several/many other systems. However, I probably had to upgrade pysetuptools (a possible Slackware problem), and certainly had to install the Python things colorama, ply, django, sympy, and SQLite had to be present. These six things are dependencies that are not part of basic Python itself, that you should really list right on your front page that they are dependencies, or it appears unprofessional and will frustrate even expert users  if they do not know a lot about Python.

**Comment by dchmelik** [comment]
Anyway, I was able to make a SlackBuild and get Mathics running... but another thing I had to do, that Mathics setup does not take care of, is setup.py intialize. People building packages for distributions will have to find out and decide what to do about this additional setup step (only documented when you intially run Mathics), and they may not all be knowledgeable enough about where setup.py should go on the system for users to use to create their database... and it could be done differently for users and for people setting up Mathics to be used maybe system-wide on some server, which they would also have to know a lot about the particular system. Hopefully the .tar.gz deals with some/all these issues from this and my last post, but some of it should be included in your lists and documentation areas. I could not access Mathics yet on my PC's test webserver, but was glad to get it running on the command line and see that it works so far, for simple arithmetic. Mathics is a very interesting project, the sort I want to get involved in, though I do not know much Python.

**Comment by bnjones** [comment]
@dchmelik, can you help me understand what's going wrong? The `setup.py` script is just input to setuptools which is a fairly standard way to distribute Python packages. It should automatically download and install all the dependencies.

I agree some installation instructions in the package would help. I'll try and find time to write some soon.

If you need to make a slackbuild or some other distro package, you can either do an installation with setup.py and read its output to see what it's doing, or just read the dependencies straight out of setup.py:
```python
# General Requirements
INSTALL_REQUIRES += ['sympy==0.7.3', 'django >= 1.6, < 1.7', 'ply>=3.4',
                     'argparse', 'python-dateutil', 'colorama',
                     'interruptingcow']
```
You can find the package names there on PyPI, but for things like django and sympy you can usually also use a distro package if you already have one, as long as it's the right version.

> another thing I had to do, that Mathics setup does not take care of, is setup.py intialize.

This has been fixed in 0.7 - when you run mathicsserver, it will create the database automatically if it doesn't exist, so there's no need to run setup.py initialize.

> Actually, the argparse thing was a well-known error with Python 2.7 itself that affects lots of dependent software, and because of that, you should probably not have argparse in setup.py

I think argparse is in setup.py because it isn't included in pre-2.7 versions of Python. If we want to support 2.6 I think we need to keep this.

**Comment by dchmelik** [comment]
As I had said, I built the SlackBuild (how I was installing Mathics, not just letting it install everything on my system... I also built one for Interruptingcow) and ran Mathics; nothing is going wrong. The setup.py does not download and install dependencies though, and the dependencies should really be listed and be able to be installed as other packages. I had to install all of them from unofficial packages for Slackware--not all distributions have these, though Slackware probably has more development software than any other (almost a DVD full, and hundreds or thousands of unofficial packages). I guess you are right about argparse, but when I built with Python 2.7, I had to remove argparse from the list.

**Comment by bnjones** [comment]
If you let me know which Slackware packages you had to install I'll add it to the installation instructions (or if you prefer you could create a pull request to do this)

**Comment by dchmelik** [comment]
It was not just adding package; I had to build another... but instructions should not depend on any one distribution, other than maybe a most minimalist one, even 'Linux from Scratch'... Slackware is minamlist in default interface style, but not in how much Slackware has (or has available unofficially). This is my note of what I had to do, which should be described (where applicable): 'remove argparse from setup.py; change sympy to 0.7.5 in setup.py, build interruptingcow, install pysetuptools, python-dateutil, colorama, ply, django, sympy, install shell script to make database for user'. I am not releasing this SlackBuild (nor submitting it to slackbuilds.org for people to install with the unofficial sbopkg installer) because I do not know Python, and I got a lot of help from someone who also does not know much Python... I mentioned it Freenode ##slackware & #slackbuilds and on slackbuilds-l, but no one has chosen to take it over yet. If anyone else here can, you can ask me for what I have written so far. Actually, slackbuilds.org and maybe Sbopkg are by some members of the Slackware team, but anyone can submit software to it for the installer, so the builds are not official (some become official).

**Comment by sn6uv** [comment]
I've removed argparse unless running Python 2.6, see PR #259 and added a note about the dependencies to the [Installing page](https://github.com/mathics/Mathics/wiki/Installing) in the wiki (which is linked to on the main github page).
