### ISSUE TITLE
mathics-0.6.0rc1.tar.gz problems

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#241]
The stable release for POSIX-based systems, mathics-0.6.0rc1.tar.gz (which I finally found with a lot of work--there still should be direct/clear links on mathics.org and on github.com) has several problems. It apparently contains the .zip file described to be for the Windows version, doubling the tarball's size. Some long-time POSIX-based system programmers say it is 'unforgivable' for a tarball to not have a directory/folder in it that has all its files, rather than some of the files being in its root like some old .zips such as of small software on DOS, but the tarball is arranged like one of those rather than a more professionally done tarball, so decompressing it clutters one's home directory and makes it difficult for various conventional package-building methods that expect tarballs to only have a root directory. My friend who was helping me make the SlackBuild also commented you have Python files in the .zip not in the tarball, such as spark.py (not sure if this is really a problem or the file is Windows-specific). Finally, the README.rst ('rst'?) is outdated with no instructions (or in any other text file)--I had to look at setup.py. After I had gone through the process of successfully building, by messing around and finding all the dependencies, from the .zip, I found the .tar.gz and that it had instructions in the PDF... so also, having no visible link on the sites to the tarball, and no instructions where a programmer would expect, could be described as problems. If nothing else, someone should probably at least remove the .zip from the .tar.gz if serving no purpose in it.

**Comment by bnjones** [comment]
Thanks for your candid feedback. Most of the problems you've identified have been fixed in the latest release which can be found at https://github.com/mathics/Mathics/releases/latest.

I think we could definitely benefit from some installation instructions in `README.rst`. I'll try and write some soon. If you have some Slackware-specific instructions to contribute (names of packages etc) that would be very helpful.
