### ISSUE TITLE
Sum[2^-x,{x,1,inf}] Should Return 1

### ISSUE THREAD

**Issue by BenWoodworth** [mathics/Mathics#245]
Sum[2^-x,{x,1,inf}] should return 1, but it returns 1-2^-inf. They're the same thing, but there's room for simplification, as x^-inf for all real x is zero.

**Comment by sn6uv** [comment]
Hey Ben,

The reason that Mathics isn't making this simplification is that (positive real) infinity is `Infinity` not `inf`, see the [Mathics documentation](http://www.mathics.net/doc/reference-of-built-in-symbols/arithmetic-functions/infinity/). Try this command with `Infinity` instead:
```
In[1]:= Sum[2^-x, {x, 1, Infinity}]
Out[1]= 1
```
Mathics doesn't know what to do with `inf` and treats it as an unknown.
