### ISSUE TITLE
yacc table file version is out of date

### ISSUE THREAD

**Issue by lj8385174** [mathics/Mathics#246]
while the 0.7rc initializing in ubuntu 14.04, it says: "yacc table file version is out of date"

**Comment by sn6uv** [comment]
This has been patched alteady but the new version hasn't been released. The temporary workaround is to install Mathics from github

**Comment by sn6uv** [comment]
Mathics 0.8 has been [released](https://github.com/mathics/Mathics/releases/tag/0.8) with this issue fixed.

**Comment by varon** [comment]
I received this issue on both 0.8 and the github master branch.

```
~/github/Mathics> git show HEAD --oneline
34c2ded Merge pull request #283 from sn6uv/pep8

~/github/Mathics> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
~/github/Mathics> python setup.py initialize
running initialize
WARNING: yacc table file version is out of date

```

Is there a workaround?

**Comment by sn6uv** [comment]
@varon, you don't need to run setup.py initialize anymore. If you're still having issues feel free to open a new issue.
