### ISSUE TITLE
Flatten lacks some functionality

### ISSUE THREAD

**Issue by wolfv** [mathics/Mathics#251]
I just coded some list functionality for Mathics, and noticed that unfortunately Flatten seems to lack some functionality:

```
>> Flatten[{{1,2,3}, {4,5,6}, {7,8,9}}] 
 = {1, 2, 3, 4, 5, 6, 7, 8, 9} // Correct!
>> Flatten[{{1,2,3}, {4,5,6}, {7,8,9}}, {2}]
: Level to be flattened together in {2} should be a non-negative integer.
Out[2]= Flatten[{{1, 2, 3}, {4, 5, 6}, {7, 8, 9}}, {2}, List]

Expected Result:
{{1,4,7},{2,5,8},{3,6,9}}
```

I tried to fix it but couldn't wrap my head completely around where the issue exactly is. Flatten seems to be a pretty generic function in Mathics.

Otherwise, cool stuff! 

Wolf

**Comment by sn6uv** [comment]
The way Mathics evaluation works is rules are applied first. The `Flatten[expr_, n_] -> Flatten[expr, n, List]` rule is being applied but `{2}` is not an integer so Mathics doesn't know what to do and reports an error.

**Comment by wolfv** [comment]
Is there another Wolfram Language Spec this was based on? Because with the latest, "my" syntax should work. 

Also, could you show me how to flatten the second dimension? I wasn't able  to find another way to do it (ie. I tried:  `Flatten[{{1,2,3}, {4,5,6}}, 1, {2}]` )

**Comment by sn6uv** [comment]
I'm reading through [the online docs](https://reference.wolfram.com/language/ref/Flatten.html) trying to get my head around what `Flatten` is spposed to do when the second argument is a list.

**Comment by wolfv** [comment]
Let me know if I can be of any help. 

As I understand, the list contains dimensions along which to flatten. 

cf: ![selection_087](https://cloud.githubusercontent.com/assets/885054/8127728/5255323a-10f9-11e5-98d9-fc55bf4d6c3c.png)
