### ISSUE TITLE
Simplify desimplifies again sometimes apparently

### ISSUE THREAD

**Issue by wolfv** [mathics/Mathics#254]
Using Simplify on a simple equation like 

`a*x^2+b*x^2` yields no simplification.

However, adding a return after the first simple simplification call gives the expected result of 

`x^2 (a + b)`

```
        try:
            result = sympy.simplify(result)
            return from_sympy(result) # this
        except TypeError:
            # XXX What's going on here?
            pass
        result = sympy.trigsimp(result)
        result = sympy.together(result)
        result = sympy.cancel(result)
        result = from_sympy(result)
        return result
```

Cheers,

Wolf

**Comment by syockit** [comment]
The culprit is `sympy.cancel`. I have no idea why it does that.

**Comment by sn6uv** [comment]
Looks like that `XXX` line was a fix for an old PyPy sympy bug. The sympy simplify algorithm has improved significantly since this code was written (2012) so might make sense to only call `sympy.simplify` here. I'll do some tests.

**Comment by sn6uv** [comment]
I was able to trigger the `TypeError` calling `Simplify` on `x f[{y}]`. Looks like there's still a bug in sympy to handle.

**Comment by sn6uv** [comment]
Figured it out. Sympy recreates objects during simplify. Because we override `__new__` the arguments aren't correct.
