### ISSUE TITLE
Logical expressions behave inconsistently/incorrectly

### ISSUE THREAD

**Issue by latkin** [mathics/Mathics#260]
Encountered this via web usage, have not tried with a local client.  Chrome 43.0.2357.124

Here is a minimal example of equivalent logical expressions behaving inconsistently:

![image](https://cloud.githubusercontent.com/assets/5943573/8258338/fc9f9f0e-1668-11e5-9159-cd5cd05f4ab5.png)

Here is a slightly more complex example, showing logical expressions behaving very inconsistently.  The final example looks to be completely wrong.

![image](https://cloud.githubusercontent.com/assets/5943573/8258469/ed1a839a-1669-11e5-851a-cc76dc13c485.png)

**Comment by sn6uv** [comment]
Thanks for reporting this.

This looks like a combination of two things to me. Equal is flattening it's arguments when it shouldn't:
```Mathematica
In[1]:= Hold[Equal[0, 0] == True] // FullForm
Out[1]= Hold[Equal[0, 0, True]]
```
expected
```Mathematica
Hold[Equal[Equal[0, 0], True]]
```
The second one is a bug in the evaluation of the flattened arguments
```Mathematica
In[2]:= Equal[0, 0, True]
Out[2]= 0 == 0 == True
```
expected
```Mathematica
0 == True
```

The second example is similar,
```Mathematica
In[3]:= Hold[(0 == 0) != (2 == 0)] // FullForm
Out[3]= Hold[Inequality[0, Equal, 0, Unequal, Equal[2, 0]]]
```
expected
```Mathematica
Hold[Unequal[Equal[0, 0], Equal[2, 0]]]
```
which also evaluates incorrectly
```Mathematica
In[4]:= Unequal[Equal[0, 0], Equal[2, 0]]
Out[4]= True != False
```
expected
```Mathematica
False
```

**Comment by sn6uv** [comment]
The parsing issue actually affects all flat operators, e.g. `Plus[a, b] + c` parses as `Plus[a, b, c]` which is wrong.
