### ISSUE TITLE
mathics.org instructions are out of date

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#262]
The instructions on mathics.org still mention `initialize.py` which has been deprecated since v0.6.

**Comment by sn6uv** [comment]
Alternate landing page https://mathics.github.io/Mathics/ references up to date installation instructions in the wiki see: https://github.com/mathics/Mathics/wiki/Installing

**Comment by limeblack** [comment]
@sn6uv There are four links displayed on the following page.

https://github.com/mathics/Mathics/releases/tag/v0.8

The first two do not contain a setup.py file and therefore do not work according to the directions.

**Comment by sn6uv** [comment]
mathics.org now directs to mathics.github.io which has the correct instructions. Thanks @poeschko !
