### ISSUE TITLE
Table with symbolic bounds

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#267]
```Mathematica
Table[k, {k, 1, n}]
Table::iterb: Iterator does not have appropriate bounds.
Table[k, {k, 1, n, 1}]
```

Should not print an error.

**Comment by wolfv** [comment]
This doesn't work in Mathematica either, as far as I can tell.

What's the expected outcome?

**Comment by sn6uv** [comment]
Ah, this issue is probably invalid then. I wasn't able to compare against Mathematica. I'll investigate further

**Comment by wolfv** [comment]
I think the Programming Cloud has a free account where you can execute Mathematica commands. 

https://programming.wolframcloud.com

**Comment by sn6uv** [comment]
As suggested by @wolfv, this issue is invalid.
