### ISSUE TITLE
ImportError: <module 'mathics.server' has no 'main' attribute>

### ISSUE THREAD

**Issue by mywtfmp3** [mathics/Mathics#288]
After installation, running "mathicserver" gives following errors. "mathics" program runs perfectly, though.
$mathicsserver
File "/usr/local/bin/mathicsserver", line 9, in <module>
    load_entry_point('Mathics==0.8', 'console_scripts', 'mathicsserver')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2195, in load
    raise ImportError("%r has no %r attribute" % (entry, attr))
ImportError: <module 'mathics.server' from '/usr/local/lib/python2.7/dist-packages/Mathics-0.8-py2.7.egg/mathics/server.pyc'> has no 'main' attribute

**Comment by crushedice2000** [comment]
I have the same problem.

**Comment by sn6uv** [comment]
I haven't been able to reproduce this problem yet. Could you share some more details about your system? E.g. 
- Operating system (is it up to date?)
- Python intepreter version
- version of setuptools
- version of django
- output of `mathics --version`.

**Comment by mywtfmp3** [comment]
`$:uname -a`
`Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux`
`$:python --version`
`Python 2.7.9`
python-setuptools: 5.5.1-1
python-django: not installed
`$:mathics --version`
`Mathics 0.8 on CPython 2.7.9 (default, Mar 1 2015, 12:57:24) using SymPy 0.7.6, mpmath 0.19`

**Comment by sn6uv** [comment]
I'm finally able to reproduce this. Will investigate.

**Comment by sn6uv** [comment]
fix #298 waiting to be merged. Thanks for reporting this
