### ISSUE TITLE
mathicsserver error 

### ISSUE THREAD

**Issue by limeblack** [mathics/Mathics#289]
@sn6uv I'm unable to run mathicsserver in TCL.  I run

    sudo mathicsserver -p 314

and when visiting it with Firefox I get the following error.

http://i.stack.imgur.com/IGL2S.png
http://i.stack.imgur.com/W7dOZ.png

This should fix the error but doesn't http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

**Comment by sn6uv** [comment]
I'm not sure what's responsible for this. I'd guess that the windows default encoding isn't utf-8

could you try
```
import sys
sys.getdefaultencoding()
```

in your python2 intepreter and post the results?

**Comment by limeblack** [comment]
@sn6uv I get 'ascii' as the default, but I have no way of changing the default encoding for the entire operating system that I know of. 

I think we need to go in a manually change the encoding for all the files that the error appears.

**Comment by sn6uv** [comment]
Good to hear that you fixed it.

Are you having trouble running Mathics on Windows natively? I've tested the latest release (under Win7) and AFAIK there are no outstanding issues running on Windows.

**Comment by limeblack** [comment]
@sn6uv I'm closing this for now, although you should really post that there is Windows support if it works.  Please take a look at this when you get a chance.
https://github.com/mathics/Mathics/issues/290

**Comment by limeblack** [comment]
@sn6uv do you mind posting a guide for Windows then before I close this issue?

For example where is mathics installed after you run `python setup.py install`?
