### ISSUE TITLE
Sum[2^x, {x, 1, y}] returns -2 + 2 2^y

### ISSUE THREAD

**Issue by limeblack** [mathics/Mathics#291]
This is almost a duplicate of [this](https://github.com/mathics/Mathics/issues/245), but I believe he just misposted.

`Sum[2^x, {x, 1, y}]` returns `-2 + 2 2^y` while the correct answer is `2 (-1 + 2^y)`.

**Comment by sn6uv** [comment]
Does it not work? [It works fine for me](http://mathics.angusgriffith.com/#cXVlcmllcz1TdW0lNUIyJTVFLXglMkMlMjAlN0J4JTJDJTIwMSUyQyUyMHklN0QlNUQ=)

**Comment by limeblack** [comment]
@sn6uv It was version .6.

It is still slightly wrong it seems like its trying to factor but fails.

`Sum[2^x, {x, 1, y}]` returns `-2 + 2 2^y` while the correct answer is `2 (-1 + 2^y)`.

**Comment by sn6uv** [comment]
The point is that it should rewrite `2 * 2^y` as `2^(y+1)`?
