### ISSUE TITLE
WARNING: yacc table file version is out of date

### ISSUE THREAD

**Issue by varon** [mathics/Mathics#294]
I cannot run Mathics under Ubuntu 14.04.3.

```
~/github/Mathics> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```

Initially, I tried the release version, which didn't work, after which I tried the git version.

```
~/github/> git clone https://github.com/mathics/Mathics.git
~/github/>cd Mathics
~/g/Mathics> python mathics/main.py 
WARNING: yacc table file version is out of date
sudo python setup.py install
~/g/Mathics> mathicsserver
WARNING: yacc table file version is out of date

```

**Comment by sn6uv** [comment]
Looks like you are using a newer version of ply. To confirm
```python
>>> import ply
>>> ply.__version__
'3.6'
```

It looks like the tables are being regenerated. This will take some time (~15 min on my machine). We should upgrade the table version and upgrade the version of ply required in setup.py. No word of this change on the [ply news announcement page](http://www.dabeaz.com/ply/).
