### ISSUE TITLE
DensityPlot regression

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#303]
I've noticed a major issue with `DensityPlot` outputs in the latest version of Mathics.

Screenshots are taken with Chrome but the behaviour under Firefox is similar.

Current master:
![densityplot_issue_chrome](https://cloud.githubusercontent.com/assets/1217643/11014467/ff3a7d0a-8536-11e5-8de3-e2f34c949730.png)
Mathics 0.6:
![densityplot_working](https://cloud.githubusercontent.com/assets/1217643/11014461/9d908158-8536-11e5-9f3e-4d4f01cad0aa.png)

**Comment by sn6uv** [comment]
Looks like this was introduced by #238

**Comment by sn6uv** [comment]
The problem is that the svg gradient renderer expects a certain ordering of polygons [0]. The incorrectly coloured region has been adaptively sampled and extra polygons added.

Inserting rather than appending the polygons should solve this issue (although there is a performance cost). 

[0] http://www.svgopen.org/2011/papers/18-Advanced_Gradients_for_SVG/mesh_order.svg

**Comment by sn6uv** [comment]
Commit 9463f9e is a workaround that disables recursion in `DensityPlot` by default. It's still possible to trigger this by explicitly requesting e.g. `MaxRecustion -> 2` so I'm leaving this open for now

**Comment by GarkGarcia** [comment]
This was fixed.
