### ISSUE TITLE
Can't solve Integral involving If[cond, f[x],g[x]] and Abs[x] functions.

### ISSUE THREAD

**Issue by DaniloRezende** [mathics/Mathics#306]
Maybe I'm not using it right. But it seems unable to solve a few simple integrals below:

> > > Integrate[Abs[x],{x,-1,1}]
> > > ∫1−1Abs[x]x
> > > 
> > > relu:=If[#>0,#,0]&
> > > Integrate[relu[x],{x,-1,1}]
> > > ∫1−1If[x>0,x,0]x

Any comments/suggestion to get these integrals right?
Best

**Comment by sn6uv** [comment]
Unfortunately Mathics doesn't handle integrals where the domain should be partitioned. The reason for this appears to be that SymPy (the library used to perform the computation) can't perform these integrals:
```python
>>> sympy.integrate(sympy.Abs(sympy.Symbol('x')), (sympy.Symbol('x'), -1, 1))
Integral(Abs(x), (x, -1, 1))
```

The solution would be to add this functionality to SymPy (or if it's already present, figure out how we can use it).

In the meantime, if you partition the domain manually it will work:
```mathematica
In [1]: Integrate[-x, {x, -1, 0}] + Integrate[x, {x, 0, 1}]
Out[1]: 1
```

**Comment by GarkGarcia** [comment]
Hey. This was apparently fixed the latest versions of SymPy.
