### ISSUE TITLE
Context bug in multiline inputs

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#328]
Evaluating
```
Begin["MyContext`"]
x = 1
End[]
```
as a single cell (in the website) puts `x` in the `Global` context not `MyContext`, while evaluating it in 3 separate cells behaves correctly. This is because the entire cell string is parsed before the context is set and so the symbol lookup is wrong in the parser.

Solving this is not completely straightforward.

I have a fix for this in my 'RefactorEvaluation' branch but maybe there's a better way.

**Comment by bnjones** [comment]
I was going to suggest doing something like 507584756058f1 but IMO the approach you've taken in RefactorEvaluation is better - especially `parse_lines` and support for `Syntax::` messages

**Comment by sn6uv** [comment]
One downside is that I'll have to replicate some of the `wait_for_line` functionality in the lexer anyway, see 5bf3f71457ecd016c27628af37b0081fbeaf2a46 for comments and I'll have to do the same for strings. I was hoping to use `parse_lines` more generally in main.py but it's a bit messy.

**Comment by sn6uv** [comment]
fixed by #329
