### ISSUE TITLE
% should return the correct value for expressions with surpressed output

### ISSUE THREAD

**Issue by triggerNZ** [mathics/Mathics#331]
Behaviour:
```
In[1]:= x=67-5;
In[2]:= %
In[3]:= 
```

This is inconsistent with mathematica, which would output 62 for %, even though In[1] ended with a semicolon

**Comment by sn6uv** [comment]
The relevant section from the MMA docs: `expr1; expr2;` returns value `Null`. If it is given as input, the resulting output will not be printed. `Out[n]` will nevertheless be assigned to be the value of `expr2`.
