### ISSUE TITLE
Associations not implemented

### ISSUE THREAD

**Issue by Piruzzolo** [mathics/Mathics#364]
when evaluating this:
`<|a -> x, b -> y, c -> z|>`

it yields
`Syntax::invalid: Invalid syntax at or near token <.`

meaning that it cannot even parse associations

**Comment by sn6uv** [comment]
@Piruzzolo I'm not sure what your code is supposed to be. It doesn't run on mathematica either:
```
    In[1]:= <|a -> x, b -> y, c -> z|>
    Syntax::sntxb: Expression cannot begin with "<|a -> x, b -> y, c -> z|>".
```

**Comment by Piruzzolo** [comment]
In Mathematica 10.0 it returns
`<|a -> x, b -> y, c -> z|>`
and spawns the hinting bar with "value of key", "extract parts", "convert to rules" etc...
It must be a well-formed expression, since I took it from [http://reference.wolfram.com/language/ref/Association.html](url)

**Comment by sn6uv** [comment]
It looks like a new feature in mathematica 10.0 (I'm using 9.0). It's not implemented in Mathics yet.

**Comment by Piruzzolo** [comment]
It could be implemented using python's dictionary data structure, I think

**Comment by Piruzzolo** [comment]
It requires to make some changes to the parser in order to recognize the syntax, as well as introduce some basic routines. I think it's not really suitable for newcomers, at least until these changes are made

**Comment by sn6uv** [comment]
I think implementing `Associations` shouldn't be too difficult. Yes, making the parser changes is a little more involved.

**Comment by sn6uv** [comment]
It's not even documented in the language spec: https://reference.wolfram.com/language/tutorial/OperatorInputForms.html

**Comment by sn6uv** [comment]
I've made the parser changes. See [my `Association` branch](https://github.com/sn6uv/Mathics/tree/Association).

@Piruzzolo do you want to have a go at implementing this?

**Comment by Piruzzolo** [comment]
@sn6uv  I can try

- no rules: returns `Association[a, b, c]`, Trace[] says `{}`
- missing close tag: returns `Syntax::tsntxi: "a->x|>" is incomplete; more input is needed.`
- missing opening tag: returns `Syntax::tsntxi: "a->x|>" is incomplete; more input is needed.`
- nested Associations: returns `<|x -> <|a -> b|>|>`, Trace[] says `{{{{a->b,a->b},Association[a->b],<|a->b|>},x-><|a->b|>,x-><|a->b|>},Association[x-><|a->b|>],<|x-><|a->b|>|>}`

**Comment by sn6uv** [comment]
What if you wrap them in Hold (so just the parser runs)? 

For `Hold[<|a, b|>] // FullForm` I get `Hold[Association[a, b]]`.

**Comment by Piruzzolo** [comment]
I get the same output

**Comment by sn6uv** [comment]
Great! For the nested example too?

**Comment by Piruzzolo** [comment]
`Hold[<|x -> <|a -> b|>|>] //FullForm` returns `Hold[Association[Rule[x,Association[Rule[a,b]]]]]`

**Comment by sn6uv** [comment]
Great. @Piruzzolo do you want to have a go at implementing the `Association` function?

**Comment by Piruzzolo** [comment]
I'll have a go, but it'll require some days to figure out how to interact with existing code (I'm pretty much a newcomer in Mathics). So, expect some question :smile:

**Comment by sn6uv** [comment]
No worries, I'm happy to answer them.

**Comment by Piruzzolo** [comment]
@sn6uv To begin with, I'm implementing StringReverse[]. Do you developers have a room on IRC? Mailing list? Or what?

**Comment by sn6uv** [comment]
@Piruzzolo There's a google groups page https://groups.google.com/forum/#!forum/mathics-devel and also #mathics on freenode. I'm not familiar with slack but maybe it's worth looking into.

**Comment by sn6uv** [comment]
@Piruzzolo I've set up a slack team. Send me an email at mathics@angusgriffith.com and I'll add you to the team if you're still interested.

**Comment by GarkGarcia** [comment]
This was recently implemented.
