### ISSUE TITLE
Derivative of vector-valued function

### ISSUE THREAD

**Issue by abrock** [mathics/Mathics#375]
Derivative calculation works for scalar-valued functions:

In[56]:= p[x_] := x^2
In[57]:= p'[x]
Out[57]= 2 x

But not for vector-valued functions:

In[58]:= p[x_] := {x^2}
In[59]:= p'[x]
Out[59]= {0}

I was expecting {2x}.

**Comment by abrock** [comment]
Integration in contrast works just fine:

`In[68]:= Integrate[{t, t^2}, {t,0,1}]`
`Out[68]= {1 / 2, 1 / 3}`

**Comment by bnjones** [comment]
Another example:

```
In[7]:= D[{#^2}, #]
Out[7]= {0}

In[8]:= D[{x^2}, x]
Out[8]= {2 x}
```
I think this is related to this rule in mathics/builtin/calculus.py:
```python
 'D[{items___}, x_?NotListQ]': 'D[#, x]& /@ {items}',
```
When this is applied to `D[{#^2}, #]`, `x` gets bound to `#` and interpolated directly into a `Function` expression, which I think is where this goes wrong. We end up with `D[#^2, #^2]` which evaluates to zero (which isn't right either but that's not related to this issue).

There might be some other issues here but a short-term fix is to avoid slots in these rules, so we can properly handle taking derivatives of slot expressions.

**Comment by bnjones** [comment]
This should now be fixed. Thanks for reporting this!
