### ISSUE TITLE
After Installation of Mathics I get the message: "s\builtin\system.py", line 15, in <module>     from mathics import version_string ImportError: cannot import name 'version_string'"

### ISSUE THREAD

**Issue by niewie1964** [mathics/Mathics#383]
Is this issue known to anyone?

I use Windows 10 and have installed the following python scripts:

![fehler01](https://cloud.githubusercontent.com/assets/19391929/15294832/20aa850a-1b8e-11e6-9ced-b844e909ab7b.jpg)

The complete output is here:

C:\Programme\python35\Scripts>mathics
Traceback (most recent call last):
  File "C:\Programme\python35\Scripts\mathics-script.py", line 9, in <module>
    load_entry_point('Mathics==0.9', 'console_scripts', 'mathics')()
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources__init__.py", line 2355, in load
    return self.resolve()
  File "C:\Program Files\Python35\lib\site-packages\pkg_resources__init__.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics__init__.py", line 7, in <module>
    from mathics.builtin import (
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\builtin__init__.py", line 7, in <module>
    from mathics.builtin import (
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\builtin\system.py", line 15, in <module>
    from mathics import version_string
ImportError: cannot import name 'version_string'

Thank you,

Andreas

**Comment by sn6uv** [comment]
Hi Andreas,
That's not an error I've seen before. As far as I know mathics hasn't been tested on windows 10. Can you tell me briefly what you did to install?

**Comment by niewie1964** [comment]
Hi Angus,

I installed Python 3.5. And I loaded Mathics from Mathics.org for Windows.

I installed it obeying the instructions on: https://github.com/mathics/Mathics/wiki/Installing

Before I extracted the zip files to a new directory an ran setup.py install. All worked well.

The ImportError occures when starting

C:\Python\Scripts\mathicsserver -p 314   or   C:\Python\Scripts\mathics

Thanks,

Andreas

**Comment by sn6uv** [comment]
I haven't got Win10 so I can't debug this myself. Can you run python 3.5 and run 

```
>>> import mathics
>>> mathics.__file__
'/home/angus/Mathics/mathics/__init__.py'
```
I think it should be `C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\__init__.py`.

Can you also post the contents of that` __init__.py` file (both files if it's a different location).

**Comment by niewie1964** [comment]
Microsoft Windows [Version 10.0.10586]
(c) 2016 Microsoft Corporation. Alle Rechte vorbehalten.

C:\WINDOWS\system32>python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mathics
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\__init__.py", line 7, in <module>
    from mathics.builtin import (
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\builtin\__init__.py", line 7, in <module>
    from mathics.builtin import (
  File "C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\builtin\system.py", line 15, in <module>
    from mathics import version_string
ImportError: cannot import name 'version_string'
>>>


That is what happens after starting Python and start "import mathics"

Thank you,

Andreas

**Comment by niewie1964** [comment]
Init in C:\Program Files\Mathics0.9\mathics:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from __future__ import absolute_import

from mathics.builtin import (
    algebra, arithmetic, assignment, attributes, calculus, combinatorial,
    comparison, control, datentime, diffeqns, evaluation, exptrig, functional,
    graphics, graphics3d, inout, integer, linalg, lists, logic, numbertheory,
    numeric, options, patterns, plot, physchemdata, randomnumbers, recurrence,
    specialfunctions, scoping, strings, structure, system, tensors)

from mathics.builtin.base import (
    Builtin, SympyObject, BoxConstruct, Operator, PatternObject)

from mathics.settings import ENABLE_FILES_MODULE

modules = [
    algebra, arithmetic, assignment, attributes, calculus, combinatorial,
    comparison, control, datentime, diffeqns, evaluation, exptrig, functional,
    graphics, graphics3d, inout, integer, linalg, lists, logic, numbertheory,
    numeric, options, patterns, plot, physchemdata, randomnumbers, recurrence,
    specialfunctions, scoping, strings, structure, system, tensors]

if ENABLE_FILES_MODULE:
    from mathics.builtin import files, importexport
    modules += [files, importexport]

builtins = []
builtins_by_module = {}


def is_builtin(var):
    if var == Builtin:
        return True
    if hasattr(var, '__bases__'):
        return any(is_builtin(base) for base in var.__bases__)
    return False

for module in modules:
    builtins_by_module[module.__name__] = []
    vars = dir(module)
    for name in vars:
        var = getattr(module, name)
        if (hasattr(var, '__module__') and
            var.__module__.startswith('mathics.builtin.') and
            var.__module__ != 'mathics.builtin.base' and
            is_builtin(var) and not name.startswith('_') and
            var.__module__ == module.__name__):     # nopep8

            instance = var(expression=False)

            if isinstance(instance, Builtin):
                builtins.append((instance.get_name(), instance))
                builtins_by_module[module.__name__].append(instance)


# builtins = dict(builtins)

mathics_to_sympy = {}
sympy_to_mathics = {}

box_constructs = {}
pattern_objects = {}
builtins_precedence = {}


def add_builtins(new_builtins):
    for var_name, builtin in new_builtins:
        name = builtin.get_name()
        if isinstance(builtin, SympyObject):
            mathics_to_sympy[name] = builtin
            if builtin.sympy_name:
                sympy_to_mathics[builtin.sympy_name] = builtin
        if isinstance(builtin, BoxConstruct):
            box_constructs[name] = builtin
        if isinstance(builtin, Operator):
            builtins_precedence[name] = builtin.precedence
        if isinstance(builtin, PatternObject):
            pattern_objects[name] = builtin.__class__
    builtins.update(dict(new_builtins))

new_builtins = builtins
builtins = {}
add_builtins(new_builtins)


def get_module_doc(module):
    doc = module.__doc__
    if doc is not None:
        doc = doc.strip()
    if doc:
        title = doc.splitlines()[0]
        text = '\n'.join(doc.splitlines()[1:])
    else:
        title = module.__name__
        for prefix in ('mathics.builtin.', 'mathics.optional.'):
            if title.startswith(prefix):
                title = title[len(prefix):]
        title = title.capitalize()
        text = ''
    return title, text


def contribute(definitions):
    # let MakeBoxes contribute first
    builtins['System`MakeBoxes'].contribute(definitions)
    for name, item in builtins.items():
        if name != 'System`MakeBoxes':
            item.contribute(definitions)

    from mathics.core.expression import ensure_context
    from mathics.core.parser import all_operator_names
    from mathics.core.definitions import Definition

    # All builtins are loaded. Create dummy builtin definitions for
    # any remaining operators that don't have them. This allows
    # operators like \[Cup] to behave correctly.
    for operator in all_operator_names:
        if not definitions.have_definition(ensure_context(operator)):
            op = ensure_context(operator)
            definitions.builtin[op] = Definition(name=op)

**Comment by sn6uv** [comment]
Just to make sure, that's the contents of `C:\Program Files\Mathics0.9\mathics\__init__.py`?

**Comment by niewie1964** [comment]
Yes, this is the file in the directory

C:\Program Files\Mathics0.9\mathics\__init__.py

**Comment by sn6uv** [comment]
Ah, we've found the problem then.

The proper `mathics/__init__.py` is being overwritten by `mathics/builtin/__init__.py`. This wrong file doesn't have `version_string` so it crashes.

In fact I'm not sure why there is an init file in that location at all.

Do you have the correct `C:\Program Files\Python35\lib\site-packages\mathics-0.9-py3.5.egg\mathics\__init__.py`?

**Comment by niewie1964** [comment]
No, I don´t have this directory. There are several ´__init__.py´files in my structure, but non of them contains a ´version_string´.

![image](https://cloud.githubusercontent.com/assets/19391929/15427499/c1f7b93c-1e95-11e6-9dcf-16032ef39700.png)

**Comment by niewie1964** [comment]
.. cuntinued:

![image](https://cloud.githubusercontent.com/assets/19391929/15427544/23005266-1e96-11e6-9975-1572a1d3c38d.png)

**Comment by niewie1964** [comment]
But there is a file "version.py" in the directory "C:\Program Files\Mathics0.9\mathics"

which contains the code:

#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

__version__ = '0.9'
