### ISSUE TITLE
sign bug in list form of Power

### ISSUE THREAD

**Issue by poke1024** [mathics/Mathics#398]
`-5^4` gives `-625`

but `{2, -5} ^ {3, 4}` gives `{8, 625}`

**Comment by sn6uv** [comment]
I think the behaviour is correct actually. The precedence of `Minus` is below that of `Power`. It agrees with MMA9 at least.

**Comment by poke1024** [comment]
It's correct indeed. And I really should have noticed that 4 is not even odd.
