### ISSUE TITLE
Sum[Sin[i 2 Pi/3], {i, 1, \[Infinity]}] raises UnicodeEncodeError

### ISSUE THREAD

**Issue by Piruzzolo** [mathics/Mathics#431]
It parses \[Infinity] when alone in the cell, but raises

`UnicodeEncodeError: 'ascii' codec can't encode character u'\u221e' in position 21: ordinal not in range(128)`

with lots of other exception stuff. It might be a problem with ascii codec.

**Comment by sn6uv** [comment]
This seems to be specific to Python 2.

**Comment by Piruzzolo** [comment]
`\[Minus]` yields 
`Syntax::sntufn: Unknown unicode longname "Minus" (line 1 of "<notebook>").` 
`Syntax::sntxb: Expression cannot begin with "\[Minus]" (line 1 of "<notebook>").`

it might be somehow related

**Comment by sn6uv** [comment]
@Piruzzolo The `\[Minus]` issue is unrelated. `Minus` is just missing from `named_characters` in `mathics/core/characters.py`.
