### ISSUE TITLE
Problem with MathML output in Firefox

### ISSUE THREAD

**Issue by Piruzzolo** [mathics/Mathics#467]
When running Mathics on Firefox 47 (but older version may behave this way too) it yields
`MathML must be formed by a <math> element, not <a0:math>`.

To reproduce: write any valid Mathics expression and evaluate.

On Chrome it works well. It may be a problem with Firefox's built-in MathML support.

**Comment by sn6uv** [comment]
Hi, thanks for the report. Which version of Mathics are you using?

I'm unable to reproduce this:
![2016-07-30-202921_2560x1440_scrot](https://cloud.githubusercontent.com/assets/1217643/17272354/9d46b7a0-5694-11e6-96fc-6f9afa2668e4.png)

**Comment by Piruzzolo** [comment]
I used the site you're running, https://mathics.angusgriffith.com

**Comment by sn6uv** [comment]
Strange, it works for me and the code looks to be okay.

Is it every query?
What OS are you running?
Do you have any add-ons that could be interfering?

**Comment by Piruzzolo** [comment]
It's every query, I'm running Windows (but doesn't work also in Ubuntu 15.10). I have a couple of addons (stylish and adsblock), but it didn't work before installing them.

**Comment by sn6uv** [comment]
What does the HTML look like, can you post a snippet?

Is the MathML code being garbled somehow (`a0:` inserted?). Can you post that too?

**Comment by Piruzzolo** [comment]
That's the HTML for "x" as input (dumped only queriesContainer):
```
<div xmlns="http://www.w3.org/1999/xhtml" id="queriesContainer">
    <ul id="queries">
        <li id="query_0" class="query">
            <ul class="query" id="">
                <li class="request">
                    <textarea class="request" rows="1"></textarea><span class="submitbutton" title="Submit [Shift+Return]"><span>=</span></span>
                </li>
                <li class="out">
                    <ul class="out">
                        <li class="result"><span class="MathJax_MathML" id="MathJax-Element-11-Frame" style="font-size: 133%;"><span class="MathJax_MathContainer" style="position: relative; display: inline-block; white-space: nowrap;"><span style="display: inline-block; width: 10px;"><span class="MathJax_MathML" id="MathJax-Element-12-Frame" style="font-size: 125%;"><span class="MathJax_MathContainer" style="position: relative; display: inline-block; white-space: nowrap;"><span style="display: inline-block; width: 672px;"><math xmlns="http://www.w3.org/1998/Math/MathML"><mrow><merror><mtext>MathML must be formed by a &lt;math&gt; element, not &lt;a0:math&gt;</mtext></merror></mrow></math></span></span>
                            </span>
                            <script type="math/mml" id="MathJax-Element-12">&lt;a0:math xmlns:a0="http://www.w3.org/1998/Math/MathML" xmlns="http://www.w3.org/1999/xhtml"&gt;&lt;a0:mrow&gt;&lt;a0:mstyle displaystyle="true"&gt;&lt;a0:mi&gt;x&lt;/a0:mi&gt;&lt;/a0:mstyle&gt;&lt;/a0:mrow&gt;&lt;/a0:math&gt;</script>
                            </span>
                            </span>
                            </span>
                            <script type="math/mml" id="MathJax-Element-11">&lt;math xmlns="http://www.w3.org/1999/xhtml"&gt;&lt;mstyle displaystyle="true"&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;/mstyle&gt;&lt;/math&gt;</script>
                        </li>
                    </ul>
                </li>
            </ul><span class="move"></span><span class="delete" title="Delete">×</span>
        </li>
    </ul>
</div>
```

**Comment by sn6uv** [comment]
Thanks. It looks like some of the HTML is being escaped (the `&lt;` `&gt;` stuff). I'm not sure why this is only happening. Maybe a language / encoding related thing. Can you try on another device?

**Comment by Piruzzolo** [comment]
Just tried, in Firefox (47.0) for Android (5.1.1) it works well.

**Comment by poke1024** [comment]
After merging https://github.com/mathics/Mathics/pull/480#issuecomment-241290811, maybe we should test this once more?

**Comment by Piruzzolo** [comment]
The problem is no longer present with Firefox 49, so I'd close the issue.
