### ISSUE TITLE
Check for PYTHONPATH failes

### ISSUE THREAD

**Issue by stefanhusmann** [mathics/Mathics#487]
I am packaging mathics 0.0 and the most recent git checkout for Arch Linux. The stable version works well, but recently (revision 2097 was okay) a check must have been implemented which fails.

''' bash
==> Beginne package()...
running install
Checking .pth file support in /home/haawda/paketierung/meine_Pakete/mathics-git/pkg/mathics-git/usr/lib/python2.7/site-packages/
/usr/bin/python2 -E -c pass
TEST FAILED: /home/haawda/paketierung/meine_Pakete/mathics-git/pkg/mathics-git/usr/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

```
/home/haawda/paketierung/meine_Pakete/mathics-git/pkg/mathics-git/usr/lib/python2.7/site-packages/
```

and your PYTHONPATH environment variable currently contains:

```
''
```

Here are some of your options for correcting the problem:
- You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files
- You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)
- You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:
  
  https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations

Please make the appropriate changes for your system and try again.

'''

**Comment by sn6uv** [comment]
Sorry for the delay, I've been moving countries recently.

I'm not exactly sure what's going on here. Can you run a git bisect to find the offending mathics commit?

**Comment by stefanhusmann** [comment]
I have a workaround for this: setting the PYTHONPATH explicitly.

+  export PYTHONPATH="$pkgdir"/usr/lib/python2.7/site-packages/
+  install -d $PYTHONPATH
+  python2 setup.py install --root=${pkgdir} --optimize=1

The offending commit must be somewhere after 1.0.dev.2097.g7d3fdfa.

**Comment by sn6uv** [comment]
I'm not sure what's changed on our end to cause this. AFAIK there haven't been any changes to the PYTHONPATH variable since the release of 0.9.

Since there's a workaround are you happy if I close this?
