### ISSUE TITLE
Mathics loads definitions from previous worksheets.

### ISSUE THREAD

**Issue by jaycech3n** [mathics/Mathics#510]
Steps to reproduce:
1. Clone current master of Mathics.
2. Install with `sudo python setup.py install`.
3. Launch `mathicsserver`.
4. Evaluate `a`.

Result:
`1`

???

**Comment by jaycech3n** [comment]
Even better:
![screenshot from 2016-08-27 18 24 42](https://cloud.githubusercontent.com/assets/3055653/18028601/8e695aa8-6c83-11e6-87c2-9c1d18ed2daa.png)

**Comment by Piruzzolo** [comment]
Maybe someone else set the variabile and the server does not isolate the sessions

**Comment by jaycech3n** [comment]
I don't see how that could happen, I'm the only one running the server locally and this is a completely fresh session.

**Comment by jaycech3n** [comment]
The issue seems to be that Mathics is loading definitions from a previous worksheet saved via the web interface.

I don't think this is behavior that we want; should we file this as a bug?

**Comment by GarkGarcia** [comment]
See https://github.com/Mathics3/mathics-django/issues/3 for updates.
