### ISSUE TITLE
Text can't handle spaces

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#527]
Inserting spaces into `Text` causes nothing to be displayed:
![2016-09-02-155232_1920x1080_scrot](https://cloud.githubusercontent.com/assets/1217643/18193916/7851cc7c-7125-11e6-84d3-ed4be2967655.png)

**Comment by PegasusClassSupplyShip** [comment]
It also can't handle multiplication which might explain it's cause.
![screenshot](https://user-images.githubusercontent.com/5833117/36415712-bfe6a09a-161e-11e8-8cb9-8249b442db72.jpg)

**Comment by GarkGarcia** [comment]
Currently `Text` cannot handle text at all.

**Comment by GarkGarcia** [comment]
See https://github.com/Mathics3/mathics-django/issues/2 for updates.
