### ISSUE TITLE
InputForm should escape backslash

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#538]
Example:

``` mathematica
In[1]:= InputForm["\$"]
Out[1]= "\$"
```

expected: `"\\$"`.

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/mathics/Mathics/commit/c3d82986a33b1836a63f8768a6bd0244739cf13d

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/mathics/Mathics/commit/c3d82986a33b1836a63f8768a6bd0244739cf13d
