### ISSUE TITLE
Strange prompt Mathics0.9/Python3.5.2/Windows

### ISSUE THREAD

**Issue by schloegl** [mathics/Mathics#542]
I've installed mathics 0.9 on Windows with python 3.5.2, following the instructions at
  https://github.com/mathics/Mathics/wiki/Installing "Installing Mathics (Windows)"

Starting Mathics 0.9 comes up with a strange prompt like 
  "<-32mIn[<-[1m1<-[22m]:= <-[39m"

Is there any known solution ? 
 
[mathics.test.txt](https://github.com/mathics/Mathics/files/461758/mathics.test.txt)

**Comment by sn6uv** [comment]
Looks like your terminal doesn't recognise the colour escape codes. `mathics --colors nocolor` should fix it.

Can I ask what version of windows you're running and which terminal emulator?

**Comment by TiberiumPY** [comment]
@sn6uv Windows don't have terminal emulator by default, it's standart CMD

**Comment by sn6uv** [comment]
Which version of windows are you using? I thought I'd tested this with cmd... did `--colors nocolor` fix it for you?

**Comment by schloegl** [comment]
Thanks that did solve the problem. May I suggest to add this options on this page, 
   https://github.com/mathics/Mathics/wiki/Installing
and change 
   C:\Python27\Scripts\mathics
to 
   C:\Python27\Scripts\mathics --colors nocolor
?

**Comment by sn6uv** [comment]
Done. Thanks again for reporting this
