### ISSUE TITLE
 Information: PyPy vs Python 2 benchmark :)

### ISSUE THREAD

**Issue by Yardanico** [mathics/Mathics#545]
Benchmark of Mathics shows PyPy winning by 2x-7x times almost always(except 1 or 2 cases). Even 10x time in some cases. 
https://paste.pound-python.org/show/8gDVpqnlQhHDdsKRSD9d/
Left part is PyPy result; right part is Python 2 result

**Comment by sn6uv** [comment]
Yep, Mathics has been faster under PyPy than CPython, I think since we added support for it.
