### ISSUE TITLE
Handle certain special characters in Mathics input

### ISSUE THREAD

**Issue by jaycech3n** [mathics/Mathics#549]
MMA:
```
In[1]:= a \[Minus] b
Out[1]:= a - b
```
(`\[Minus]` is replaced on the fly in input)
vs. Mathics:
```
In[1]:= a \[Minus] b
  Syntax::sntxf:
  "a " cannot be followed by "− b" (line 1 of "<notebook>").
```

We probably want `\[Minus]` to be parsed as `-` as ASCII as opposed to the unicode `\u2212`. Maybe there are other characters we should do a similar thing for too.

MMA automatically replaces such characters as they are typed in the input cell itself; we could either do the same, or else just leave it unchanged in input but evaluate the ASCII version.

**Comment by sn6uv** [comment]
Thanks for reporting this.

We don't want to modify the input to ascii because `\[Minus]` is also vaid in strings etc. Fixed this by adding `\u2212` to the tokeniser (to generate a Minus token), see a000894.
