### ISSUE TITLE
Partial Differential Equations (PDE)

### ISSUE THREAD

**Issue by schloegl** [mathics/Mathics#587]
When I asked some mathemica users about mathics, they mentioned that support for PDE is missing. Are there any plans to include PDE support in Mathics ?

**Comment by sn6uv** [comment]
We have an open issue for tracking the addition of PDE solvers, see #349. It is something that we're hoping to get into the upcoming release but the work hasn't been done yet.

**Comment by sn6uv** [comment]
PDE works is done now, see #589. Unfortunately SymPy currently only supports simple first order PDE but nevertheless it's better than before.
