### ISSUE TITLE
Minor issue with Firefox and uBlock Origin extension

### ISSUE THREAD

**Issue by Piruzzolo** [mathics/Mathics#599]
![firefox issue](https://cloud.githubusercontent.com/assets/11365978/18966300/fca3ff20-8680-11e6-9e86-f41987c003e7.gif)

**Firefox 49.0.1, uBlock Origin 1.9.10**

In Chrome, the same extension doesn't mess up the layout. Disabling the extension, the layout is fine. Don't know which filter is responsible.

Worth keeping this issue open? We may add a hint to disable ads-blocking extensions on `localhost:whatever` on the "Installing" wiki page.

**Comment by GarkGarcia** [comment]
Hey. I'm a Firefox + uBlockOrigin users and I'm not facing the issue described. I believe this was bug in uBlockOrigin.
