### ISSUE TITLE
testing optional modules

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#601]
As we increasingly add optional modules to Mathics using the `requires = (...)` approach we are introducing a number of different versions of Mathics (parameterised by which modules are present). Testing this introduces a considerable problem since in some cases (e.g. networkx and numpy) modules interact or depend on one another (even partially/optionally).

At the very least we should be testing a full version of Mathics with everything installed.

One problem to be aware of is that `llvmlite` is difficult to install on Travis (it requires a specific version of LLVM to be present on the system). numpy can also be problematic to install.

**Comment by poke1024** [comment]
Good point.
