### ISSUE TITLE
Error upon installation in Mac OS (El Capitan)

### ISSUE THREAD

**Issue by jeffreyyepez** [mathics/Mathics#651]
The installation guide on the Mathics website

https://github.com/mathics/Mathics/wiki/Installing

says that the easiest way to install Mathics is with pip:

pip install matrices

However, this command fails with the following write permission error:

 creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-pI_M68/sympy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wrHPnj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-pI_M68/sympy/
sh-3.2# 

Remarkably, this write permission error occurs even upon running the installation from root!

Is there a way to avoid this error?

Thanks

**Comment by sn6uv** [comment]
You can try installing mathics from the setup.py file. Here are the previous installation instructions https://github.com/mathics/Mathics/wiki/Installing/6b4394bb45ff06dec194211b82bd002ff101601a
