### ISSUE TITLE
Factorial2 does not simplify

### ISSUE THREAD

**Issue by vasekp** [mathics/Mathics#653]
For integral numerical arguments ≥ -1, at least, this should be easy: reusing existing implementation a Factorial2[n] is Factorial[n/2] * 2^(n/2) for n even and Factorial[n+1] / Factorial2[n+1] for n odd (reducing to previous case). Yet inputs 1!!, 2!!, 3!!, 4!!, ... stay unevaluated.

**Comment by austinprog** [comment]
@vasekp  I think this is a problem I will try and solve!
