### ISSUE TITLE
Release as a Chrome App using NaCl

### ISSUE THREAD

**Issue by gjvnq** [mathics/Mathics#657]
I know this is going to be hard and time consuming, but I think it will help many people to use Mathics more easily if they can download it through the Chrome Web Store instead of having to use the command line.

I've already seen an [IPython port](https://chrome.google.com/webstore/detail/colaboratory-notebook/pianggobfjcgeihlmfhfgkfalopndooo) running as a Chrome App using NaCl, so I imagine it will, at least, be possible without a significant code rewrite.

**Comment by limeblack** [comment]
I vote to close this issue or edit.  I believe NaCL is being deprecated in favor for WebAssembly.

https://developer.chrome.com/native-client/migration
