### ISSUE TITLE
`Repeated[a]`  causes infinite recursion

### ISSUE THREAD

**Issue by jlapeyre** [mathics/Mathics#662]
```
In[1]:= Repeated[a]
$RecursionLimit::reclim: Recursion depth of 200 exceeded.
Out[1]= $Aborted
```
Mathics 1.0
on CPython 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
using SymPy 1.0, mpmath 0.19

**Comment by rocky** [comment]
I can't remember when, but I believe @mmatera fixed this a while back. We now get: 

```
In[2]:= Repeated[a]
Out[2]= a..

```
