### ISSUE TITLE
bug with Import

### ISSUE THREAD

**Issue by Lillille** [mathics/Mathics#663]
The following command

     data = Import["C:\\0000000\\mathematica\\classeur1.csv", "CSV"]

works with MLathematica but not with Mathics under Windows7 a too long set of error to include them

**Comment by sn6uv** [comment]
Could you please upload that file, `classeur1.csv` so we can investigate.

**Comment by sn6uv** [comment]
Closing as duplicate of #660. Please refrain from opening multiple bugs for this.
