### ISSUE TITLE
ElementData[] parser error?

### ISSUE THREAD

**Issue by axkr** [mathics/Mathics#664]
The input:
`ElementData["Pd", "ElectronConfiguration"] `

and

`ElementData["Pd", "ElectronShellConfiguration"]`

shows a parser error

**Comment by sn6uv** [comment]
There was a typo in the data file `mathics/data/element.csv`. `Pd` seems to be the only affected element. Thanks for reporting this.

**Comment by axkr** [comment]
`ElementData["Pd", "AtomicRadius"] `should give `169` not `140`?

**Comment by sn6uv** [comment]
I think the reason for the discrepancy is that MMA uses different information sources. It looks like the 169 figure is a calculated number, https://dx.doi.org/10.1063%2F1.1712084 while Mathics uses an empirical measurement. Mathics's numbers are taken from Wikipedia and I can't find the original source. Do you have a better source for the 169 number or it's just to be consistent with MMA?

The covalent radius number (139) seems more accurate. According to the [Cambridge Structural Database](https://en.wikipedia.org/wiki/Cambridge_Structural_Database) it's 139 +- 6.
