### ISSUE TITLE
Simple test from Mathematica

### ISSUE THREAD

**Issue by adakite** [mathics/Mathics#669]
As a starting move from Mathematica, I tried this very simple case, which works perfectly with Mathematica: 
```
L = 15;
TMax = 100;

tsunamiEqn = 
  u /. NDSolve[{(1/(1 - 0.98*Boole[Abs[x - 3.5] < 1 && Abs[y] < 2]))*
        D[u[t, x, y], t, t] == 
       D[u[t, x, y], x, x] + D[u[t, x, y], y, y], 
      u[0, x, y] == 0.15 Exp[-(x^2 + y^2)], 
      Derivative[1, 0, 0][u][0, x, y] == 0, u[t, -L, y] == u[t, L, y],
       u[t, x, -L] == u[t, x, L]}, 
     u, {t, 0, TMax}, {x, -L, L}, {y, -L, L}][[1]];

l = Table[
   Plot3D[tsunamiEqn[fac TMax, x, y], {x, -L, L}, {y, -L, L}, 
    PlotRange -> {{-L, L}, {-L, L}, {-0.1, 0.2}}, Mesh -> 10, 
    PlotPoints -> 50, 
    PlotStyle -> {LightBlue, Specularity[White, 50]}], {fac, 0, 
    0.9, .09}];

ListAnimate[l]
```

While I understand that the plot options may differ from Mathematica to Mathics, I have issues on the computing side of the notebook:

`ReplaceAll::reps: Derivative[2, 0, 0][u][t, x, y] / (1 - 0.98 Boole[Abs[-3.5 + x] < 1 && Abs[y] < 2]) == Derivative[0, 0, 2][u][t, x, y] + Derivative[0, 2, 0][u][t, x, y] is not a valid replacement rule.`

```
Syntax::sntxf: "Plot3D[tsunamiEqn[fac TMax, x, y], {x, -L, L}, {y, -L, L}, 
         PlotRange -> {{-L, L}, {-L, L}, {-0.1, 0.2}}, Mesh -> 10, 
         PlotPoints -> 50, 
         PlotStyle -> {LightBlue, Specularity[White, 50]}]" cannot be followed by ", {fac, 0, 0.9, .09}" (line 4 of "<stdin>").
```

So the first error is due to the boundary conditions that is not acceptable for Mathics in the way it is written for Mathematica. Any thoughts about this, what did I write wrong?

Thanks for any help on my very first step with Mathics.

**Comment by sn6uv** [comment]
Unfortunately Mathics doesn't implement numerical solutions to differential equations, `NDSolve` yet. It also doesn't have `ListAnimate` either.

For now you can try some analytic solutions with `DSolve` but I know that's probably not what you're after.

**Comment by adakite** [comment]
Hey, thanks for answering. I did not realized this, thanks for pointing me out on that limitation of Mathics. For now, `DSolve` might be sufficient, but is there any roadmap of supporting `NDSolve` eventually?

**Comment by sn6uv** [comment]
It's not on the roadmap at the moment. It's something that would be great to have, I agree, but it's a huge time investment to get even a basic solver working. I don't think anyone is willing to take it on right now.

**Comment by adakite** [comment]
All right, Fair enough. Thank you for your feedbacks. I'll continue digging into Mathics anyways.
