### ISSUE TITLE
matrix multiplication and MatrixForm

### ISSUE THREAD

**Issue by WilliaMaster** [mathics/Mathics#670]
Hi,

I did some relatively simple matrix multiplications using the web interface and the lines below. Maybe I didn't get the algebra quite right or the syntax is wrong...but the displayed MatrixForm outputs seem to be incorrect. In addition I believed that Matrix A and B should yield the same result. Any ideas on that?

Thanks in advance!

M = {{Cos[m] + a * Sin[m], b * Sin[m]}, {-c * Sin[m], Cos[m] - a * Sin[m]}}
T = {{ b ^ ( -1 / 2), 0}, {a * b ^ ( -1 / 2 ), b ^ ( 1 / 2 )}}
A = T . M . Inverse[T]//Simplify
F = M . Inverse[T]
B = T . F//Simplify
MatrixForm[M]
MatrixForm[T]
MatrixForm[A]
MatrixForm[B]

**Comment by sn6uv** [comment]
It looks like a bug to me, The `T` matrix is being modified. It seems to happen when something is multiplied by it's inverse.
```mathematica
In[1]:= T = {{ b ^ ( -1 / 2), 0}, {a * b ^ ( -1 / 2 ), b ^ ( 1 / 2 )}}
Out[1]= {{1 / Sqrt[b], 0}, {a / Sqrt[b], Sqrt[b]}}

In[2]:= T . Inverse[T]
Out[2]= {{1, 0}, {0, 1}}

In[3]:= T  (* T is modified *)
Out[3]= {{b ^ (1 / 2 - 1 / 2), 0}, {a b ^ (1 / 2 - 1 / 2), Sqrt[b]}}
```

This isn't quite what's happening in the definition of `A` above but I think it's related.

**Comment by sn6uv** [comment]
Found the bug. Working on a fix now.

**Comment by sn6uv** [comment]
Fixed the bug. New output is
```
In[1]:= M = {{Cos[m] + a * Sin[m], b * Sin[m]}, {-c * Sin[m], Cos[m] - a * Sin[m]}}
Out[1]= {{a Sin[m] + Cos[m], b Sin[m]}, {-c Sin[m], -a Sin[m] + Cos[m]}}

In[2]:= T = {{ b ^ ( -1 / 2), 0}, {a * b ^ ( -1 / 2 ), b ^ ( 1 / 2 )}}
Out[2]= {{1 / Sqrt[b], 0}, {a / Sqrt[b], Sqrt[b]}}

In[3]:= A = T . M . Inverse[T]//Simplify
Out[3]= {{Cos[m], Sin[m]}, {(a ^ 2 - b c) Sin[m], Cos[m]}}

In[4]:= F = M . Inverse[T]
Out[4]= {{Sqrt[b] (a Sin[m] + Cos[m]) - a Sqrt[b] Sin[m], Sqrt[b] Sin[m]}, {-a (-a Sin[m] + Cos[m]) / Sqrt[b] - Sqrt[b] c Sin[m], (-a Sin[m] + Cos[m]) / Sqrt[b]}}

In[5]:= B = T . F//Simplify
Out[5]= {{Cos[m], Sin[m]}, {(a ^ 2 - b c) Sin[m], Cos[m]}}

In[6]:= MatrixForm[M]
Out[6]= a Sin[m] + Cos[m]   b Sin[m]
        
        -c Sin[m]           -a Sin[m] + Cos[m]

In[7]:= MatrixForm[T]
Out[7]= 1 / Sqrt[b]   0
        
        a / Sqrt[b]   Sqrt[b]

In[8]:= MatrixForm[A]
Out[8]= Cos[m]                 Sin[m]
        
        (a ^ 2 - b c) Sin[m]   Cos[m]

In[9]:= MatrixForm[B]
Out[9]= Cos[m]                 Sin[m]
        
        (a ^ 2 - b c) Sin[m]   Cos[m]
```

**Comment by sn6uv** [comment]
Thanks for reporting this! The bug was caused by copying a reference (and not value) in the matrix product code.
