### ISSUE TITLE
Comparing lists of strings returns a literal expression instead of False

### ISSUE THREAD

**Issue by ghost** [mathics/Mathics#673]
When comparing to unequal lists of strings, for example `{"a","b"}=={"b","a"}`, it returns literally that expression. Comparing equal strings returns True as normal. See [here](https://tio.run/nexus/mathics#@x9QlJlX4qBRrZSopKOUpFRra1sNpHSA3FrN//8B).

**Comment by GarkGarcia** [comment]
This has been fixed apparently. Mathics returns `False` now.
