### ISSUE TITLE
Transpile to JavaScript

### ISSUE THREAD

**Issue by ClementNerma** [mathics/Mathics#679]
I'm currently looking for a good CAS engine that works in browser, without a server. After seeing this great project I'm wondering if it would be possible to transpile it to pure JavaScript code ?

If Mathics uses command-line instructions that may be complicated, but else would it be possible to realize it using PyPy or any other transpiler ? The main question is about performances : I saw Mathics computes fast, very fast, maybe too fast for Python, so does it use any not-python code or compiled optimizer, like C++ or a JIT ? If so, it'll be a problem too for transpiling...

If it's possible to make it working directly in a browser, it'd be great because all calculations would be performed by the client's computer and wouldn't be limited by the server's capacity.

**Comment by wolfv** [comment]
Maybe you could get it running in PyPy.js? As far as I remember, Mathics is pure python, as is sympy (without symengine). 

In the future I think the most promising project is Batavia (https://github.com/pybee/batavia/) to get python in the browser. But it's too far from being feature complete.

**Comment by ClementNerma** [comment]
Thanks, I'll try it. For now I'm wondering if this would work by transpiling SymPy to C++ using Nuitka and then to JavaScript using Emscripten (but performances will be very, very, very bad I think).

**Comment by lschumm** [comment]
I've maintained Batavia a bit and am quite interested in Mathics–I'll give converting Mathics a try.
