### ISSUE TITLE
Undo and Redo in the web interface

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#68]
Something notoriously bad in Mathematica is the limited undo/redo. I think it would be great if we could add this feature to the web interface somehow. 

P.S. how do I tag this as an enhancement?

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/mathics/Mathics/commit/543596d2e6ac3192bea1c61211d4fe89c6a3ed45 (apparently)
