### ISSUE TITLE
security issue: Mathics apparently must run as root

### ISSUE THREAD

**Issue by dchmelik** [mathics/Mathics#681]
I tend to run software as a non-privileged user, and wrote a Mathics initialization script that does so. After I upgraded to Django 1.8.16, Mathics crashed because something (Django?) expects to run as root.  I chowned my mathics installation directory to a user, then it worked. That shouldn't be how software works that people expect to trust (having to do a minor ‘hack’ to get it to work, i.e. something average users may not want to deal with or even figure out.)

**Comment by sn6uv** [comment]
Thanks for reporting this.

A root user is not required to run Mathics. Root is only necessary for installing Mathics system-wide (after which non-root users can run it).

I'm unable to reproduce this issue.  Can you share your initialization script?

**Comment by dchmelik** [comment]
#!/bin/sh
# start/stop/restart Mathics

#restart Mathics:
mathics_restart()
{
  killall mathicsserver
  su u -c "mathicsserver -e"&
}

# start GIMPS:
mathics_start()
{
  su u -c "mathicsserver -e"&
}

# stop Mathics:
mathics_stop()
{
  killall mathicsserver
}

case "$1" in
'restart')
  mathics_restart
  ;;
'start')
  mathics_start
  ;;
'stop')
  mathics_stop
  ;;
*)
  echo "usage $0 start|stop|restart"
esac

**Comment by sn6uv** [comment]
Sorted this with the reporter.
