### ISSUE TITLE
Limit Error

### ISSUE THREAD

**Issue by codingskynet** [mathics/Mathics#686]
When I enter the command "Limit[x/Abs[x], x->0]",
the program returns "-1"

But "Limit[x/Abs[x], x->0]" doesn't have two-sided limit(Direction->-1: 1, Direction->1:-1) because it doesn't exist.

Is it bug?

**Comment by sn6uv** [comment]
Looks like a bug to me, interestingly, Mathematica 11 gets this wrong too:
```
In[1]:= Limit[x/Abs[x], x->0]
Out[1]= 1
```

**Comment by wolfv** [comment]
sympy 1.3 has the `+-` option. When evaluating with this option, limits raises a ValueError if the limit does not exist.

When doing the upgrade to sympy 1.3, I'll integrate this new function.

**Comment by GarkGarcia** [comment]
I imagine this was fixed when in integrated SymPy 1.6
