### ISSUE TITLE
TypeError when using Eigen{vector, system, values}

### ISSUE THREAD

**Issue by BudRz** [mathics/Mathics#690]
For this matrix problem

`In[1]:= A := {{1,-2},{2,1}};`

when I do either

`In[2]:= Eigenvalues[A]`

or

`In[2]:= Eigensystem[A]`

or

`In[2]:= Eigenvectors[A]`

I get the error:

> TypeError: Invalid comparison of complex -1 + 2*I

Matrices that had real eigenvalues had no such issue.

Is there a workaround for this problem?

**Comment by GarkGarcia** [comment]
This has been fixed.
