### ISSUE TITLE
StringSplit doesn't work correctly

### ISSUE THREAD

**Issue by somebody1234** [mathics/Mathics#698]
From the [documentation page](https://reference.wolfram.com/language/ref/StringSplit.html):

```mathematica
StringSplit["11a22b3", _?LetterQ]
```

**Comment by sn6uv** [comment]
Yes, we don't support the full string expression language. I think it's just a matter of translating this expression to a regexp but I'm not sure how we can handle the general case. 

It's possible to work around this with e.g. 

```
In[1]:= StringSplit["11a22b3", RegularExpression["[a-zA-Z]"]]
Out[1]= {11, 22, 3}
```
