### ISSUE TITLE
Use Mathematica as FrontEnd for Mathics

### ISSUE THREAD

**Issue by limeb** [mathics/Mathics#711]
So probably my favorite thing about Mathematica is the editor.  I have found the web interface lacking of mathics.  Could anyone give advice on how to make Mathics the kernel for Mathematica?

I have node.js development experience not so much Python but might be able to help.

**Comment by mmatera** [comment]
I think mma front end connects to the kernel via Mathlink, so the first challenge to make it works would be to define a Mathlink interface to the Mathics Kernel. But it is not the only Challenge: graph interfaces does not have any to do with the Mathics one. On the other hand, why would you use the mma front end and not it's kernel?

**Comment by limeblack** [comment]
I like the Mathematica editor it has support for double click to select something the web interface does not.  It also supports auto formatting.  Technically it wouldn't have to implement mathlink to allow me to use Mathematica as a front end although I'm not sure which would be easier.  Yes you are right there are api differences.

**Comment by axkr** [comment]
Maybe this plugin can be used?
https://github.com/halirutan/Mathematica-IntelliJ-Plugin

You can also use  PyCharm in the same IntelliJ IDEA environment

**Comment by mmatera** [comment]
Another possibility in which I was working on is to use a  jupyter notebook interface. 
 
https://github.com/mmatera/iwolfram

With this, certain features of the front end of wolfram mma are available, and it works in a more or less transparent way both with wolfram as well as with mathics kernel.

**Comment by limeblack** [comment]
@axkr the formatting works differently from what I have gathered.  I have used the intelij plugin though and I believe still have it installed.

**Comment by GarkGarcia** [comment]
I think this is out of scope for now.
