### ISSUE TITLE
--execute does not work as expected

### ISSUE THREAD

**Issue by Yurlungur** [mathics/Mathics#712]
When I run 

```shell
mathics -e "Print[1+1];" -script myfile.mathics
```

where `myfile.mathics` simply contains the line `Print["Hello"];` I get

```shell
In[1]:= Print[1+1];
6
```

And `myfile.mathics` does *not* execute. This seems counter to the information printed with `mathics -h`. What *should* happen and what I would like to be able to do is that `Print[1+1];` should be executed and then `myfile.mathics` should be run as a script.

I'm happy to help fix this if I can figure out where this functionality is being implemented. Can you point me to the right part of the code?

**Comment by GarkGarcia** [comment]
Hey @Yurlungur. If you're still interested, the bug is probably somewhere in [main.py](https://github.com/mathics/Mathics/blob/master/mathics/main.py).

I'm not sure the bug is still present thought. I'll investigate it.

**Comment by Yurlungur** [comment]
Wow. I'd completely forgotten about this. Sure, I'm still interested, if the bug is still present. I'll take a look.

**Comment by rocky** [comment]
@Yurlungur 

Here is what I am currently getting: 

```
$ mathics -e "Print[1+1];" -script /myfile.mathics
2
None
```
Personally I find mxing `-e` and `-script` and `Print` weird. What was it you were really trying to do?

**Comment by Yurlungur** [comment]
Honestly, it's been so long that I don't remember why I wanted to do this. An easy fix might be to just put that one can't mix these flags into the help message and move on.

**Comment by TiagoCavalcanteTrindade** [comment]
@Yurlungur I'm fixing it.

**Comment by rocky** [comment]
Personally, I'd like to understand the use case and then document this assuming it is useful. Or if it matches the behavior of the WL command line options that is useful to know too. 

Also a unit test would be nice.
