### ISSUE TITLE
Precision 

### ISSUE THREAD

**Issue by gtimoshaz** [mathics/Mathics#713]
I used version 0.9 with sympy 0.7.6, and 0.9^10000 was 2.66 (a bit more digits) * 10^(-458)
Now I updated to 1.0 with sympy 1.0, and 0.9^10000 is 0.

**Comment by GarkGarcia** [comment]
> 0.9^10000

You can use rational numbers to get _absolute_ precission and then cast the results to floats using `N` (which can take the precision as a parameter).
