### ISSUE TITLE
Log[a,0]  should return -Infinity / Log[a]

### ISSUE THREAD

**Issue by axkr** [mathics/Mathics#714]
`Log[a,0] `

should return 

`-Infinity / Log[a]`

**Comment by wolfv** [comment]
I think that'd need to be fixed in sympy.

**Comment by wolfv** [comment]
With new sympy this return `ComplexInfinity/Log[a]` – I can't judge wether this is correct or not however.

**Comment by GarkGarcia** [comment]
> With new sympy this return `ComplexInfinity/Log[a]` – I can't judge wether this is correct or not however.

This example is in the test cases, so I imagine it's correct.
