### ISSUE TITLE
Solving equations with lists

### ISSUE THREAD

**Issue by abrock** [mathics/Mathics#720]
I want to solve (nonlinear) sets of equations. Mathics can do this if I write the problem like this:

> In[8]:= Solve[{x==0,y==0},{x,y}]
> Out[8]= {{x -> 0, y -> 0}}

But I have functions which have lists as results and mathics doesn't solve them:

> In[21]:= f[{x_,y_}]:={x,y}
> In[23]:= f[{0,0}]
> Out[23]= {0, 0}
> In[24]:= Solve[{f[x,y]=={0,0}},{x,y}]
> Out[24]= Solve[{f[x, y] == {0, 0}}, {x, y}]

**Comment by selairi** [comment]
It doesn't solve lists as equations:

`In[1]:= Solve[{{x,y}=={0,0}}, x]
Out[1]:= Solve[{{x,y}=={0,0}}, x]`

**Comment by GarkGarcia** [comment]
This is not the behaviour of [Wolfram's Solve](https://reference.wolfram.com/language/ref/Solve.html), so this is out of scope.
