### ISSUE TITLE
Error in Apart function

### ISSUE THREAD

**Issue by fpe-pedraza** [mathics/Mathics#725]
Apart[x/(2 x + a^2)]
mathics result: 0
Correct result: 1/2 - a^2/(2 (a^2 + 2 x))

**Comment by wolfv** [comment]
Mathics usingn sympy 1.3 as backend seems to get it right! 
I've opened PR #756 

![screenshot from 2018-10-09 11-58-12](https://user-images.githubusercontent.com/885054/46662029-a527ba80-cbba-11e8-8c78-8f1a72a2d51c.png)
