### ISSUE TITLE
Limit - Bad behavior

### ISSUE THREAD

**Issue by lordjail** [mathics/Mathics#727]
A limit at `Infinity` using the `x` as a variable is computed correctly, but using a `t` gives a wrong answer.
`Limit[(1+x^2)/(2+x^2),x->Infinity]`  (*This returns 1*)
`Limit[(1+t^2)/(2+t^2),t->Infinity]`  (*This returns 0.98916*)
I tried computing other limits at `Infinity` and the problem is still the same.

See the attached screenshot when using the [online interface](https://mathics.angusgriffith.com/#cXVlcmllcz1MaW1pdCU1QigxJTJCeCU1RTIpJTJGKDIlMkJ4JTVFMiklMkN4LSUzRUluZmluaXR5JTVEJnF1ZXJpZXM9TGltaXQlNUIoMSUyQnQlNUUyKSUyRigyJTJCdCU1RTIpJTJDdC0lM0VJbmZpbml0eSU1RA==):
![limits](https://user-images.githubusercontent.com/38534659/39001528-c5b3102a-43f6-11e8-9eae-a718c2111cd3.png)

**Comment by wolfv** [comment]
This works locally for me. Have you tried only the online interface?

**Comment by lordjail** [comment]
Yes, I only tried the online interface. But I have tried the same commands again now it is working correctly. It seems that, consciously or unconsciously, someone has fixed it already.

**Comment by wolfv** [comment]
I'm unsure how the online version is implemented exactly, but it might be that the `t` was somehow defined in a different way beforehand. 

Cheers!
