### ISSUE TITLE
Division Inaccuracy

### ISSUE THREAD

**Issue by Simulationism** [mathics/Mathics#728]
Hello,
I found out that divisions with certain values lead to problematic inaccuracies on mathics.net
Example:

a=24.2;
b=6.05;
a/b
  3.99999999999999
Floor[a/b]
  3

Due to this tiny division inaccuracy the floor-function yields 3 instead of 4 which is a major error.
However this doesn't always happen, other values work fine like:

c=24.1;
d=6.025;
c/d
  4
Floor[c/d]
  4

I'm curious why the 1st example has so many decimal places but the 2nd one has none.
Here is a screenshot just in case that's required:

![division inaccuracy](https://user-images.githubusercontent.com/38859149/39431082-eaf1a026-4c8f-11e8-8f2c-a56d090e3e95.JPG)

**Comment by wolfv** [comment]
Indeed, this might be related to sympy and python versions. Generally, floating point math is *hard*.

However, the mathics/python/sympy version hosted on mathics.angusgriffith.com seems to get it right: 

![screenshot from 2018-10-09 11-56-04](https://user-images.githubusercontent.com/885054/46661891-51b56c80-cbba-11e8-8f22-897969ba780f.png)
