### ISSUE TITLE
Sign[ ]  function is missing!

### ISSUE THREAD

**Issue by cbabc** [mathics/Mathics#729]
Surprisingly there is no sign function in Mathics!
Since Mathics is advertised as an open alternative to Mathematica I expected to find such a simple fundamental function.  For me it's very important.

**Comment by wolfv** [comment]
Would you be interested in helping out with the implementation of this function?

**Comment by wolfv** [comment]
Or rather, `Sign[]` is implemented in the most recent version of Mathics. However, it might not be available from the online interfaces.

You can always install Mathics locally and use the `Sign` function there.
