### ISSUE TITLE
Simplify[  ] doesn't completely simplify 

### ISSUE THREAD

**Issue by cbabc** [mathics/Mathics#730]
For example, it won't simplify more than 0.5 x + 0.5 y.
That is 2 muls and 1 add.

Simplify[ 0.5 x + 0.5 y ] should give 0.5 * (x + y) 
which is 1 mul and 1 add.

**Comment by wolfv** [comment]
Factor[0.5 x + 0.5 y] will give you the desired result.

Mathematica also does not do this simplification by default

![screenshot from 2018-10-09 11-51-51](https://user-images.githubusercontent.com/885054/46661592-c76d0880-cbb9-11e8-9ac3-315a37900d98.png)

**Comment by weakit** [comment]
shouldn't this be closed?

**Comment by GarkGarcia** [comment]
> shouldn't this be closed?

lol, yes
