### ISSUE TITLE
DSolve can't solve the simpler differential equation.

### ISSUE THREAD

**Issue by danielanphd** [mathics/Mathics#731]
If I put a simple question: (asking to solve y'=y), I get an error:
DSolve[y'[t]== y[t],y,t]    
DSolve::litarg:

    To avoid possible ambiguity, the arguments of the dependent variable in y'[t] == y[t] should literally match the independent variables.
    DSolve[y′[t]==y[t],y,t]

However, if I try
DSolve[y'[t]== t+y[t],y,t]   
It does solve it. 

Strange.

**Comment by adakite** [comment]
I tried similar test as:

```
A = {{4, -6}, {1, -1}};
X[t_] = {x[t], y[t]};
system = X'[t] == A.X[t]
sol = DSolve[system, {x, y}, t]
```
and got
```
DSolve::deqx: Supplied equations are not differential equations of the given functions.
Out[8]= DSolve[{x'[t], y'[t]} == {W y[t] - D x[t], -W y[t] + D x[t]}, {x, y}, t]
```
where Mathematica gives:
```
{{x -> Function[{t}, ((D E^(t (-D - W)) + W) C[1])/(
     D + W) - ((-1 + E^(t (-D - W))) W C[2])/(D + W)], 
  y -> Function[{t}, -((D (-1 + E^(t (-D - W))) C[1])/(
      D + W)) + ((D + E^(t (-D - W)) W) C[2])/(D + W)]}}
```

**Comment by GarkGarcia** [comment]
> If I put a simple question: (asking to solve y'=y), I get an error:
> DSolve[y'[t]== y[t],y,t]
> DSolve::litarg:
> 
> ```
> To avoid possible ambiguity, the arguments of the dependent variable in y'[t] == y[t] should literally match the independent variables.
> DSolve[y′[t]==y[t],y,t]
> ```
> 
> However, if I try
> DSolve[y'[t]== t+y[t],y,t]
> It does solve it.
> 
> Strange.

Your example now works.
