### ISSUE TITLE
Test failures in the master branch (CI broken!)

### ISSUE THREAD

**Issue by skirpichev** [mathics/Mathics#746]
It seems, test suite was broken long tme ago, an example on [recent PR](https://github.com/mathics/Mathics/pull/745):
https://travis-ci.org/mathics/Mathics/jobs/417843009
(Problem happens on the before_install stage, which apparently wasn't affected by mentioned PR.)

Another issue is random segfaults in pypy tests:
https://travis-ci.org/mathics/Mathics/jobs/417843005
Also, it looks this happened before, see https://github.com/mathics/Mathics/pull/722

**Comment by wolfv** [comment]
Fixed!

**Comment by skirpichev** [comment]
@wolfv, probably you should close this issue in related pull request.  I.e. with a [commit message](https://help.github.com/articles/closing-issues-using-keywords).

Or it's intentional and issue is not fixed really?

**Comment by wolfv** [comment]
I can't close it as I'm not a maintainer and not the creator of the issue.
@poeschko could probably close it

Le 9 oct. 2018 11:55 AM, "Sergey B Kirpichev" <notifications@github.com> a
écrit :

**Comment by skirpichev** [comment]
> I can't close it as I'm not a maintainer and not the creator of the issue.

You can close as I had explained above.

Anyway, I expect that you believe it's fixed.  So, I'll close it.
