### ISSUE TITLE
Crashing bug: Pattern-matching on Orderless symbol

### ISSUE THREAD

**Issue by rebcabin** [mathics/Mathics#749]
Please consider the following two lines, which crash mathics:

    SetAttributes[or, Orderless]
    or[p, p] /. or[p_, p_] :> p

They work fine in Mathematica.

**Comment by sealemar** [comment]
Fixed in https://github.com/rebcabin/Mathics/pull/1

**Comment by wolfv** [comment]
Is that a fork? I've tried to contact the maintainers of Mathics to get some more maintainership going...

**Comment by rebcabin** [comment]
Yes, It's a fork. I see no significant activity in this repo for the last couple of years. I will continue to file issues here just in case someone comes home, but, in the meantime, we will work over in our fork.

**Comment by wolfv** [comment]
Let's see if we can summon @sn6uv @poeschko @bnjones to see if we can take over maintainership ... it would be sad to see Mathics fade away.

**Comment by rebcabin** [comment]
I can't let it fade away: I have no other "good-enough" tool for conditional term rewriting, which I need for formal methods. I can't ask collaborators to purchase Mathematica (well, I can ask, but they won't). But I can get them to use Python and sympy and I can get them to adopt an alternative syntax like Mathematica's.

**Comment by poeschko** [comment]
Do you want to open a pull request to this repository? I'd be happy to merge it.

**Comment by rebcabin** [comment]
I just opened a PR. It should include that fix, plus a few other minor ones I made.
