### ISSUE TITLE
Updates to Sympy version?

### ISSUE THREAD

**Issue by sdwfrost** [mathics/Mathics#750]
I'd like to have both the latest Mathics and the latest Sympy in the same environment; Mathics is currently fixed to use Sympy 1.0, while Sympy is currently on 1.3rc1. What are the breaking changes, if any?

**Comment by skirpichev** [comment]
You can try to remove hard wired version requirement (==1.0) and see what happens.  I did some experiment with adding support of the different CAS kernel (Diofant) in [this branch](https://github.com/skirpichev/Mathics/tree/diofant-experiment).  CI tests pass.  Your case looks to be much simpler.

Unfortunately, this project seems to be dead.

**Comment by wolfv** [comment]
I've locally tried this and only 4 tests or so are failing. I hope to make a PR with the newest sympy version very soon.

**Comment by wolfv** [comment]
I've created a PR: #756 Let me know if one of you guys has input.

**Comment by GarkGarcia** [comment]
I guess this is fixed then (?)
