### ISSUE TITLE
Reverse function is not working

### ISSUE THREAD

**Issue by esopsis** [mathics/Mathics#752]
If I go to http://www.mathics.net/ and put in Reverse[{a, b, c, d}] (or really anything with Reverse as far as I can tell) and hit shift-enter, it just outputs Reverse[{a, b, c, d}] unevaluated.

**Comment by wolfv** [comment]
This works locally. Can you check in a local installation?

Also note that the tests are passing.

**Comment by esopsis** [comment]
Hey I'm sorry I don't actually use Python that much these days, and looking through the install process I'm not sure if it's going to take me 10 minutes to get this running locally or if it's going to take me a frustrated hour of troubleshooting to get it to work. 

Perhaps I'm not tech savvy enough really to get what it's supposed to do or whatever, all I know is I click on the mathics link, type in Reverse[{a, b, c, d}], hit shift+enter, and it does not in fact reverse the digits like it does in Mathematica (whereas many other functions seem to work fine for me.) Do you need me to work through the install process to get this issue worked out? I can try and find time to work it out I guess.  Sorry I'm kinda new to this stuff.

**Comment by wolfv** [comment]
You can try online at https://mathics.angusgriffith.com/ which has the newer version of Mathics that properly supports reverse:

![screenshot from 2018-10-10 09-42-26](https://user-images.githubusercontent.com/885054/46720478-ed091900-cc70-11e8-9339-280a0e1ae6ea.png)


Cheers!

**Comment by wolfv** [comment]
hey, 

I've set up the latest version of Mathics to run in mybinder.org 

https://mybinder.org/v2/gh/wolfv/Mathics/binder?urlpath=proxy%2F1234%2F

Feel free to check wether the code in question works in this environment.

**Comment by GarkGarcia** [comment]
It looks like there's nothing to fix in here (?). I'll close the issue.
