### ISSUE TITLE
Gamma[1/2] evaluates to 0

### ISSUE THREAD

**Issue by TobiSchluter** [mathics/Mathics#754]
Gamma[1/2] == Sqrt[Pi] yet it evaluates to zero if I enter it on http://www.mathics.net

**Comment by TobiSchluter** [comment]
Less importantly, expression which involve the Gamma function see Gamma replaced with Factorial unconditionally, which looks a bit odd once you start manipulating derivatives.

**Comment by wolfv** [comment]
This works locally for me. Most likely due to sympy being more up to date.

**Comment by wolfv** [comment]
Even online this seems to work fine: 
![screenshot from 2018-10-09 11-45-16](https://user-images.githubusercontent.com/885054/46661146-e0c18500-cbb8-11e8-8bb7-16994d487435.png)

**Comment by TobiSchluter** [comment]
Sure. Note that I explicitly mentioned a different, more official sounding webpage -- which happens to be terribly out of date, as i now know.

**Comment by wolfv** [comment]
yep, that one is not under my control. I don't know whose it is ... maybe @poeschko knows?

**Comment by TobiSchluter** [comment]
![screen shot 2018-10-14 at 12 53 56](https://user-images.githubusercontent.com/11887541/46912438-5a3de680-cfb0-11e8-9a59-c2f870e078ca.png)
I'm reopening this, because if I open the documentation on the "good" website, it actually points to the "bad" website, see the attached screenshot. The "good" website has a certificate error to boot, so the "bad" website looks more trustworthy than the "good" website.

This is a different bug (documentation issue at least), so if you prefer I can open a new issue.

**Comment by wolfv** [comment]
yes, if you could file a new bug for this. 

a good idea could be to make Mathics run on mybinder.org – then it would stay up to date and be hosted by folks at UC Berkeley.

**Comment by TobiSchluter** [comment]
Moved the website problems to #762
