### ISSUE TITLE
Coefficient[] not implemented yet

### ISSUE THREAD

**Issue by celis** [mathics/Mathics#765]
Coefficient[] not implemented yet 
https://reference.wolfram.com/language/ref/Coefficient.html

**Comment by jojordan3** [comment]
I would like to help with this issue if no one is working on it yet.

**Comment by austinprog** [comment]
@celis @jojordan3  

Was this implemented already? I found it in algebra.py and was able to perform it successfully via the command line version of Mathics.

**Comment by austinprog** [comment]
#676

**Comment by GarkGarcia** [comment]
> @celis @jojordan3
> 
> Was this implemented already? I found it in algebra.py and was able to perform it successfully via the command line version of Mathics.
> 
> Issue #676

Indeed it was! It just hasn't being released yet.
