### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by suhr** [mathics/Mathics#768]
The last release was in 2016. It would be nice to have a new one.

**Comment by adakite** [comment]
Are we sure Mathics is still developed and maintained by someone? 

Issues don't get much replies, low rate on files updates, I'm worried....

**Comment by suhr** [comment]
@poeschko merges pull requests, but looks like there's no active developers anymore. And that's indeed very unfortunate.

**Comment by mmatera** [comment]
Actually, there was several pr in the last months. I think is more a matter
that @poeschko <https://github.com/poeschko> has time to check them out.

M

**Comment by JoseCarlosGarcia95** [comment]
I added support to optimizations last month but he must be busy forma replying pr

**Comment by wolfv** [comment]
Sometimes we can summon him :) I asked for shared maintainership but it didn't work out.
We just need to occasionally ping him.

**Comment by sn6uv** [comment]
@wolfv I've just sent you an invite to be a maintainer if you're still intetrested

**Comment by slel** [comment]
@sn6uv 

Thanks for renewing the letsencrypt certificate for your website,
restoring access to your website and blog.

- https://angusgriffith.com
- https://blog.angusgriffith.com/

The mathics page on your website gives "504 Gateway timed out",

- https://mathics.angusgriffith.com/

maybe you could add a redirection to the mathics home page?

On the PyPI page for IMathics,

- https://pypi.org/project/imathics/

please also fix the "homepage" field by removing the extra www
```
- http://www.mathics.github.io/
+ http://mathics.github.io/
```

If you no longer have time, could you add one or several
extra maintainers with enough access to do such changes?

I can volunteer to help if you and/or @wolfv would be interested.

**Comment by suhr** [comment]
Because this repository is not being maintained, I have made a fork: https://github.com/suhr/Mathics

**Comment by wolfv** [comment]
Hi @suhr, 

I got maintainer rights a week or two ago, so at least we can now merge PR's.
I will soon do a conda-forge release, and will also look into how to create a new pip release.

**Comment by suhr** [comment]
@wolfv Then would you like to merge this PR: https://github.com/mathics/Mathics/pull/775?

**Comment by wolfv** [comment]
@sn6uv any chance you could add me to the pip package as well? I am going to make a release soon -- at least on conda-forge.

**Comment by mmatera** [comment]
Could you also consider add the pr #618? I think now it is ready.
M

**Comment by GarkGarcia** [comment]
See https://github.com/mathics/Mathics/issues/841 for updates
