### ISSUE TITLE
#name (slot associativity) not implemented yet

### ISSUE THREAD

**Issue by ghost** [mathics/Mathics#796]
See: https://reference.wolfram.com/language/ref/Slot.html

For example: `f[#u, #v, #u] &[<|"u" -> x, "v" -> y|>]` should output `f[x, y, z]`, but outputs the error:

> Syntax::sntxf:
> 
> "f[#u, #v, #u] &[" cannot be followed by "<|"u" -> x, "v" -> y|>]" (line 1 of "<notebook>").

in Mathics instead. Seems like `#name` for associations is not implemented yet. Possible related pull request: https://github.com/mathics/Mathics/pull/705

**Comment by GarkGarcia** [comment]
Alright, currently Mathics doesn't take name slots into account. This is something that we should fix.

This fix will involve redesigning the way associations are handled.

**Comment by GarkGarcia** [comment]
Fixed https://github.com/mathics/Mathics/commit/34a1d2a8bb92ef5232a7a0fbe76523ae25594a93
