### ISSUE TITLE
Is it possible to use curl with Mathics' web interface?

### ISSUE THREAD

**Issue by lonnietc** [mathics/Mathics#802]
Hello,

I am able to run the Mathics server but was wondering if it is possible to use curl or some type of API to send a math string to the Mathics server and then get back the Mathjax, JSON, or HTML, or SVG image of the result in a single call?

Any help would be greatly appreciated.
Thanks

**Comment by GarkGarcia** [comment]
That's entirely possible. The only issue is hosting. What you're looking for is someone who's running `mathicsserver` on their server, making it accessible via a domain name. I'm not aware of anyone who's doing this, but it's definitely possible.

**Comment by GarkGarcia** [comment]
On regards to the _single call_ thing, I don't think it's possible, at least not in the way Mathics is currently designed.

**Comment by GarkGarcia** [comment]
@lonnietc Does that answer your questions?

**Comment by lonnietc** [comment]
Hello,

Yes, thanks. We can close this item now.
