### ISSUE TITLE
I want to help with the project

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#805]
This project needs some help. Issues and PRs are pilling up and it's been more than a year since the last update to the repo.

I'd just like to know if you guys would like making me a collaborator. I could help with the review process of PR, tagging and addressing issue and fixing simple bugs.

**Comment by GarkGarcia** [comment]
@wolfv I assume you are the main contributer in here (?), that's why I keep tagging you.

**Comment by GarkGarcia** [comment]
@sn6uv @bnjones Could you take a look at this?

**Comment by suhr** [comment]
Probably it's easier to create a fork.

**Comment by GarkGarcia** [comment]
@sn6uv halp plz 😕️

**Comment by wolfv** [comment]
Hi Gark! I am still alive luckily, and yes, maintenance rights were given to me at some point. Unfortunately I also haven't properly filled that role. Do you want to be a co-maintainer?

**Comment by GarkGarcia** [comment]
> Do you want to be a co-maintainer?

I'd love to!
