### ISSUE TITLE
String based options

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#81]
The current implementation of `OptionsPattern` doesn't seem to like `String` type options. For example:

```
>> Plot[x, {x, 0, 1}, "example" -> "1"]
 = Plot[x, {x, 0, 1}, example -> 1]
```

fails. Yet: 

```
>> Plot[x, {x, 0, 1}, example -> 1]
 = -Graphics-
```

is okay.

I came across this issue when trying to implement options for `RegisterImport` such as `"DefaultElement"`.

**Comment by GarkGarcia** [comment]
This was fixed at some point.
