### ISSUE TITLE
Fix error in the Make target for mathics.pdf

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#840]
Apparently an error in the Make target for `mathics.pdf` is causing builds with `DOC="true"` to fail, as can be seen in https://travis-ci.org/github/mathics/Mathics/jobs/725204768#L6770.

**Comment by mmatera** [comment]
Yes, I was working yesterday on fixing it. The first thing would be to include in .travis.yml a line

sudo apt-get install -qq inkscape texlive-font-utils;

to install epstopdf and inkscape.
However, after that, it still show errors, maybe because the position of the directory where documentation is built.

**Comment by GarkGarcia** [comment]
> Yes, I was working yesterday on fixing it. 

Great! 

> However, after that, it still show errors, maybe because the position of the directory where documentation is built.

Yeah, TeX command-line tools tend to be behave awkwardly on regards to this sort of thing.

**Comment by rocky** [comment]
I've been meaning add a top-level Makefile and I have been meaning to look at how the docs are made.

One annoyance I currently have is that my editor (Emacs) likes to remove trailing blanks and that can mess up the tests because sometimes in docstrings that is necessary. That is another thing on my list of things to address.

**Comment by GarkGarcia** [comment]
> I've been meaning add a top-level Makefile

That would be much better than the current shell-scripts scattered around the repository.

**Comment by GarkGarcia** [comment]
@mmatera Maybe the remaining errors are related to https://github.com/mathics/Mathics/issues/609?

**Comment by mmatera** [comment]
> @mmatera Maybe the remaining errors are related to #609?

Indeed, the errors comes from #609 and the unicode chars. I think both could be filtered in the routines building the documentation. Maybe this is work for the next week...

**Comment by GarkGarcia** [comment]
Apparently https://travis-ci.org/github/mathics/Mathics/jobs/727081135#L6576 fails because of a missing pickle file... I'm not sure what it's supposed to contain.

**Comment by mmatera** [comment]
I am working with  @rocky to fix this.

**Comment by GarkGarcia** [comment]
> I am working with @rocky to fix this.

Great! Are you guys working in a PR? Which PR is it?

**Comment by GarkGarcia** [comment]
@rocky @mmatera I was able to fix the "No such file or directory error", but the docs won't compile still because of other things. Please take a look at #886 if you can.

**Comment by mmatera** [comment]
It's green now... good!

**Comment by GarkGarcia** [comment]
> It's green now... good!

Lol, it didn't work locally for some reason, but I guess I'll merge it then.

I'm not sure that's the right fix though. Essentially, the issue was caused by a missing file. The `write_latex` function expected a file named `data` to be placed under `mathics/doc/tex/`.

I'm not sure if this file was supposed to be generated before we called `write_latex`. In that case, we're probably doing something wrong in the Makefile. On the other hand, if we're on interested in checking if the docs compile, we're good. We don't actually need the file in there, we just need the information in it (which is provided by my patch).

I'd appreciate if you guys could take a look at the commit (https://github.com/mathics/Mathics/pull/886/commits/03f1e7beaaa9f475f6d3fbe9137643f9852845aa) to make sure I'm not doing anything stupid.

**Comment by mmatera** [comment]
> > It's green now... good!
> 
> Lol, it didn't work locally for some reason, but I guess I'll merge it then.
> 
> I'm not sure that's the right fix though. Essentially, the issue was caused by a missing file. The `write_latex` function expected a file named `data` to be placed under `mathics/doc/tex/`.
> 
> I'm not sure if this file was supposed to be generated before we called `write_latex`. In that case, we're probably doing something wrong in the Makefile. On the other hand, if we're only interested in checking if the docs compile, we're good. We don't actually need the file in there, we just need the information in it (which is provided by my patch).
> 
> I'd appreciate if you guys could take a look at the commit ([03f1e7b](https://github.com/mathics/Mathics/commit/03f1e7beaaa9f475f6d3fbe9137643f9852845aa)) to make sure I'm not doing anything stupid. It's quite short overall.

No, write_latex uses the data file written by test_all. I guess that for some reason, the way in which the test is called omits to save that file.

Now I am looking at it.

**Comment by GarkGarcia** [comment]
Finally fixed with https://github.com/mathics/Mathics/commit/fbebe5579ec43ca6ae48146676f8bc148b76ece7.
