### ISSUE TITLE
"TemplateDoesNotExist" error when running Mathics from PyPy3

### ISSUE THREAD

**Issue by mmatera** [mathics/Mathics#847]
I was trying to compile and run mathicsserver after compiling with pypy3, but I found the error in the web browser
"""
TemplateDoesNotExist at /

main.html
"""

**Comment by rocky** [comment]
I am seeing it in 3.7.9 as well. 

```
$ mathicsserver
Migrating database /home/rocky/.local/var/mathics/mathics.sqlite
loading symbols
Operations to perform:
  Apply all migrations: auth, contenttypes, sessions, sites, web
Running migrations:
  No migrations to apply.

database initialized sucessfully

Mathics 1.1.dev0
on CPython 3.7.9 (default, Sep  5 2020, 09:56:01) 
using SymPy 1.6.2, mpmath 1.1.0, django 1.11.29

Copyright (C) 2011-2020 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by pressing CONTROL-C

Open the graphical user interface at
http://localhost:8000
in Firefox, Chrome, or Safari to use Mathics

loading symbols
Internal Server Error: /
Traceback (most recent call last):
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/rocky/src/external-vcs/github/rocky/Mathics/mathics/web/views.py", line 67, in main_view
    return render(request, 'main.html', context)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/rocky/.pyenv/versions/3.7.9/lib/python3.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: main.html
[09/Sep/2020 03:16:51] "GET / HTTP/1.1" 500 95644
  C-c C-c^C
Goodbye!
```

This is a Djanjo error. I am guessing one of the many recent commits broken this. I don't have time to investigate though.

**Comment by rocky** [comment]
I explicitly installed Django 1.8.9 and went back to commit 0f26d9ca71d590a277c7c592e254281aae281358 and Pypy works fine for me (as does 3.7.9).

**Comment by mmatera** [comment]
Yes, I think it is related to the IMathics patch. Django's and jupyter versions of the mathics frontend were not compatible...

**Comment by rocky** [comment]
Pro tip:  When reporitng a bug please try to give the level of detail like above. It's okay for you make guesses as to what's wrong (and you may be wrong in your guess), but if you don't give the *details* the guesses just lead to red herrings.

**Comment by GarkGarcia** [comment]
> Yes, I think it is related to the IMathics patch. Django's and jupyter versions of the mathics frontend were not compatible...

Makes sense. This was a very old PR which had to be manually rebased. I probably messed something up there. My bad 😥️

**Comment by mmatera** [comment]
> Pro tip: When reporitng a bug please try to give the level of detail like above. It's okay for you make guesses as to what's wrong (and you may be wrong in your guess), but if you don't give the _details_ the guesses just lead to red herrings.

Yes, you are right, sorry.

**Comment by suhr** [comment]
I can reproduce this with ordinary Python as well.

**Comment by GarkGarcia** [comment]
I'll stop trying to merge old PRs before the milestone because it's prone to causing this kind of bug.

**Comment by rocky** [comment]
The one that I want to see and came across is https://github.com/mathics/Mathics/pull/499 And looking at that, the comments were pretty straight-forward. 

I'd be willing to look at this when I get a chance.
