### ISSUE TITLE
Fix CI configuration issues regarding llvmlite

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#861]
This a followup to https://github.com/mathics/Mathics/pull/860#pullrequestreview-486937901. Essentially, there is an (unknown) issue in the CI configuration that causes `llvmlite` to fail to find some relevant `.so` file. This prevents us from testing some features on certain platforms (CPython 3.8 and PyPy 3.6).

Up to now, we've been dealing with this issue [by simply skipping the tests that require `llvmlite`](https://github.com/mathics/Mathics/pull/860#pullrequestreview-486937901). A recent patch (https://github.com/mathics/Mathics/pull/860/commits/cb080a1ed09bdf6a5ef610d39985199f8f06423a and https://github.com/mathics/Mathics/pull/860/commits/ca74b1ed7a98da4388ee35a641e5db2b371c80fd, https://github.com/mathics/Mathics/pull/860/commits/ca74b1ed7a98da4388ee35a641e5db2b371c80fd and https://github.com/mathics/Mathics/pull/860/commits/1923b042519877f9a35d23171da673dc5e6bd81d) made it possible to tests features that require `llvmlite` on older platforms. However, this needs to be properly addressed at some point.

See https://travis-ci.org/github/mathics/Mathics/jobs/726327847 for the logs of the failing builds.

**Comment by rocky** [comment]
I should note that this does work on Ubuntu 20.4 with Python 3.8.5 and llvm-3.9-dev installed. So for CI it might just be a matter of getting the right llvm-dev installed.
