### ISSUE TITLE
Address failures in Combinatorica Package

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#867]
A number of routines fail in the recent Combinatorica Package. Go over that and fix them where possible. 

(I'll take this)

**Comment by rocky** [comment]
@GarkGarcia This shouldn't be in a 1.1 milestone. The failures are numerous and pervasive However the package is still useful and many things work. 

My suggestion is to deal with those after 1.1.

**Comment by GarkGarcia** [comment]
> @GarkGarcia This shouldn't be in a 1.1 milestone. The failures are numerous and pervasive However the package is still useful and many things work.
> 
> My suggestion is to deal with those after 1.1.

I'd like to try to address the failures before releasing the code. As you said, it's far from ideal to release buggy code. But I'm okay removing it if you feel like you won't have enough time to get everything working.

**Comment by rocky** [comment]
We can remove. I'd suggest though just having it hang out in a branch somewhere.

**Comment by rocky** [comment]
As I look at Graphs, although this may seem radical  I think that should get chucked too. It looks pretty straightforward to reimplement all of this (and do a better job) in networkx. 

As with Combinatorica it can hang out in a branch. 

Actually, now that I think of it, the code could all probably be there (in pymathics) but just not enabled.  So if someone does one to use it in its buggy state, there is something trivial like uncommenting out some code that will do the trick.

**Comment by GarkGarcia** [comment]
> We can remove. I'd suggest though just having it hang out in a branch somewhere.

That works, sure. I image removing Combinatory from master won't cause any tests to fail, so I'm inclined to that. Could you work on this? I could send you an invitation that become a project collaborator in GitHub, which would allow you to create a separate branch for Combinatorica.

> I doubt there will ever be merge conflicts with this because it is all so self-contained.

Yes, well-written commits usually don't cause conflicts (your contributions are well-written) 😀️

**Comment by GarkGarcia** [comment]
> As I look at Graphs, although this may seem radical I think that should get chucked too. It looks pretty straightforward to reimplement all of this (and do a better job) in networkx.
> 
> As with Combinatorica it can hang out in a branch.

I agree. I'm inclined to do that too. Storing Graphs in a separate branch shouldn't cause any conflicts with everything else.

> Actually, now that I think of it, the code could all probably be there (in pymathics and packages) but just not enabled.
> 
> So if someone does wants to use it in its buggy state, there is something trivial like uncommenting out some code that will do the trick.
> 
> And that may be preferable because with it there someone may be motivated to work on it. It is just that we are up front about it not being usable in a robust way.
> 
> In fact Combinatorica isn't loaded automatically. So on loading we could give a warning message on package import, but that's really already done by virtue of the errors that spew.

I would prefer to move those things to a separate branch. It's a cleaner solution, and it would make the install size smaller.

**Comment by rocky** [comment]
Sure send an invitation.

**Comment by GarkGarcia** [comment]
> Sure send an invitation.

I just realized I don't have the authority to make you a project collaborator 😅️

@wolfv Could you us out with this one? Could you make @rocky a collaborator?

**Comment by GarkGarcia** [comment]
This was postponed to 1.2. See https://github.com/mathics/Mathics/issues/912.
