### ISSUE TITLE
Update to the latest Django

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#879]
This is a follow up to https://github.com/mathics/Mathics/issues/841#issuecomment-691663855.

**Comment by rocky** [comment]
FYI https://groups.google.com/g/django-users/c/Co6qI0cdl7s

**Comment by GarkGarcia** [comment]
> FYI https://groups.google.com/g/django-users/c/Co6qI0cdl7s

Could you transcribe the relevant discussion to here? I don't have a Google account and I don't plan to create one 😅️

**Comment by GarkGarcia** [comment]
@rocky @suhr @mmatera Is there any reason for not updating to Django 3?

**Comment by suhr** [comment]
Yes: Django 3 is not an LTS version.

**Comment by mmatera** [comment]
If we do not need an specific functionality, I would keep the LTS version

**Comment by GarkGarcia** [comment]
> If we do not need an specific functionality, I would keep the LTS version

I agree. I'll try to upgrade to Django 2.2

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/mathics/Mathics/commit/c3a01606756ea1b620a8da3640fb4620b469313f.

**Comment by rocky** [comment]
I looked at the various release notes and incompatibilitiies after  Django 1.11 

In trying the various versions after 1.11 I see breakage in Firefox between Django 2.1.3 and 2.1.4.  

Looking at the [release notes for 2.1.4](https://docs.djangoproject.com/en/3.1/releases/2.1.4/) there should only be bugfixes between releases. I guess then this is an unintentional bug introduction. 

I create [branch Django-to-2.1.3](https://github.com/mathics/Mathics/tree/Django-to-2.1.3) which has these changes. 

@suhr Is Django in the reange 2.0 .. 2.1.3  okay for a NixOS package? 

@GarkGarcia Would you please check if this branch if this addresses problems you saw? 
@mmatera It would be great to merge what you have in your branch on top of this, and then if everything goes well we can merge all of this into master.

**Comment by suhr** [comment]
> @suhr Is Django in the range 2.0 .. 2.1.3 okay for a NixOS package?

No, it's too old. Beside that, it is not an LTS version.

**Comment by GarkGarcia** [comment]
> Looking at the release notes for 2.1.4 there should only be bugfixes between releases. I guess then this is an unintentional bug introduction.

This is very weird. We'll have to discuss this in today's meeting.

> @GarkGarcia Would you please check if this branch if this addresses problems you saw?

Sure. I've confirmed that the version in the branch you mentioned works fine in my machine.

**Comment by rocky** [comment]
@GarkGarcia Thanks. 

I've been trying to get it past 2.1.4 and am giving up. What I am seeing is that the hangs in waiting on a socket to be received which matches what you reported earlier. 

The sepcific images not loaded are on font-awesome-min.css icons for download and showOpen. We are using fontawesome version 4 and 5 is the stable release. Upgrading this is a pain and probably not worth it for just those two 3 icons. 

There is another [PR for Improved Workspace](https://github.com/mathics/Mathics/pull/695) that adds functionality and possibly it may get us further too. 

@suhr I am largely giving up on this one. If you can figure out a fix, go at it.

**Comment by suhr** [comment]
> @suhr I am largely giving up on this one. If you can figure out a fix, go at it.

I'll probably just disable HTTP_IF_MODIFIED_SINCE completely.

**Comment by rocky** [comment]
A PR for this so we can discuss?

**Comment by suhr** [comment]
Good news: the fix for Django 2.2 works in Django 3.1, and there's no issues with file loading.

This is the ticket describing the bug for 2.2, by the way: https://code.djangoproject.com/ticket/16099. It has nothing to do with 304 error code, just multithreading was broken.

**Comment by suhr** [comment]
So I suggest to switch to Django 3.1. It is not an LTS release, but the next release (3.2) *is* an LTS release.

**Comment by rocky** [comment]
Ok - please update your PR then.

**Comment by rocky** [comment]
And would you please rebase off of the current master do there are no rebase problems? Thanks!

**Comment by suhr** [comment]
Done.

**Comment by rocky** [comment]
See review comments. Thanks for doing!

**Comment by rocky** [comment]
I think we can put this issue to bed now. Thanks @mmatera @GarkGarcia  and @suhr !
