### ISSUE TITLE
Attributes for Predefined symbols

### ISSUE THREAD

**Issue by sn6uv** [mathics/Mathics#90]
When the attributes of a `Predefined` symbol are left undefined (or are defined as an empty tuple) this seems to get overridden with `{Protected}`. See, for example:

```
>> Attributes[$InstallationDirectory]
 = {Protected}
```

which should give 

```
In[1]:= Attributes[$InstallationDirectory]
Out[1]= {}
```

despite being defined as such in `builtin.files`.

Related: #85

**Comment by tueda** [comment]
Any updates? Some existing Mathematica packages may try to overwrite `$Path` for adding their subdirectories and fail due to this bug.

**Comment by rocky** [comment]
When not in Django, this works.
