### ISSUE TITLE
Information doesn't work in the web frontend

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#901]
A picture is worth a thousand words:

![Screenshot from 2020-09-17 20-16-04](https://user-images.githubusercontent.com/37553739/93537894-22b9e080-f923-11ea-8c39-751fd6ece62e.png)

**Comment by mmatera** [comment]
This happens only on the web interface? Or also fails in the text interface?

**Comment by rocky** [comment]
It only happens on Django, not text. It happens in 1.x as well.

**Comment by mmatera** [comment]
It seems that the problem is how a text with "\n" is printed out in the web interface. For example, I got the same error with the input

"s\na"

**Comment by mmatera** [comment]
PR #903 seems to fix this. Still we need to check what happens when a string with "\n" characters is printed...

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/mathics/Mathics/commit/c7113d3e02c065cb362e316b74b5a3479ff79920.
