### ISSUE TITLE
Update Three.js from version r52 to something closer to r120

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#904]
There are probably lots of improvements that have occurred in the last 7 years. Staring in r50 the name changes. See https://github.com/mrdoob/three.js/releases/r50 for example.

**Comment by mmatera** [comment]
We could try to just change the version and see if it does work. If not, I would keep the current version for a while...

**Comment by rocky** [comment]
I tried something like that, but I could have done it wron.. It doesn't work. 

You probably need to do read the release notes, and do it step by step or several step by  steps.

**Comment by mmatera** [comment]
What I can tell you is that once I tried to hack the code for the Iwolfram, and it was a non trivial task, even for the basic functionality. The interface has a lot of work on the top of tree.js, and I didn't expect that update it be an easy task...

**Comment by rocky** [comment]
Thanks for the information. This could be a very long-term project. I am hoping someone with an interest with this sort of stuff will come a long and help out.

**Comment by slel** [comment]
In SageMath we are lucky to have @paulmasson and recently @jcamp0x2a
contribute many Three.js upgrades and related improvements.

If someone works on Three.js in Mathics, studying what is done
in Sage may provide inspiration. Here are some links.

- [Sage 9.2 release tour](https://wiki.sagemath.org/ReleaseTours/sage-9.2): section [Graphics](https://wiki.sagemath.org/ReleaseTours/sage-9.2#Graphics)
- [Sage 9.1 release tour](https://wiki.sagemath.org/ReleaseTours/sage-9.1): section [Improvements in the Three.js 3D viewer](https://wiki.sagemath.org/ReleaseTours/sage-9.1#Improvements_in_the_three.js_3D_viewer)
- [Sage 9.0 release tour](https://wiki.sagemath.org/ReleaseTours/sage-9.0): section [Three.js is the new default 3D viewer](https://wiki.sagemath.org/ReleaseTours/sage-9.0#Three.js_is_the_new_default_3D_viewer)
- [Sage tickets about Three.js](https://trac.sagemath.org/query?order=id&desc=1&summary=~threejs&or&summary=~three.js&col=ticket&col=summary&col=reporter&col=author&col=reviewer&col=type&col=status&col=priority&col=milestone)
- [three.js in sage-devel](https://groups.google.com/forum/#!searchin/sage-devel/three.js%7Csort:date)
- [three.js in sage-release](https://groups.google.com/forum/#!searchin/sage-release/three.js%7Csort:date)
- [three.js in sage-support](https://groups.google.com/forum/#!searchin/sage-support/three.js%7Csort:date)

**Comment by rocky** [comment]
@slel Thanks for the information. This is helpful in understanding what is involved. 

As an aside, I would like to see the various CAS projects be more inter-operable. 

To that end a long-term goal after the 1.1 release (if this ever happens) is to decouple the Mathematica parser part to produce Python output that is suitable running standalone as sympy with lots of Mathics library calls. 

A short step from that is noticing where things like `Table[]` can be translated directly into say a list or list comprehension. The run-time "builtin" routine for Mathics' Table and a routine run after AST generation would probably share a lot of code in common.

If it is easier to go to sage libraries that would be cool too,

**Comment by rocky** [comment]
Fixed in https://github.com/Mathics3/mathics-django/pull/65.
