### ISSUE TITLE
Invitation from Sage Days!

### ISSUE THREAD

**Issue by wolfv** [mathics/Mathics#926]
Hi all (especially @GarkGarcia , @mmatera , @suhr )

@saraedum reached out to send an invitation to Sage Days 110 (Oct 29-30.). They are interested in having a Mathics talk! I haven't had the time to contribute much lately, but I am very happy to do this together with whoever wants. We could give a short talk about what Mathics is, how it works, what the next goals are?

https://wiki.sagemath.org/days110

**Comment by GarkGarcia** [comment]
> Hi all (especially @GarkGarcia , @mmatera , @suhr )
> 
> @saraedum reached out to send an invitation to Sage Days 110 (Oct 29-30.). They are interested in having a Mathics talk! I haven't had the time to contribute much lately, but I am very happy to do this together with whoever wants. We could give a short talk about what Mathics is, how it works, what the next goals are?
> 
> https://wiki.sagemath.org/days110

That's amazing! It's a great opportunity for us to attract attention to the project, which could help alleviate the shortage of developers interested in contributing to the project.

Unfortunately I'm not sure I'll hove time to prepare something until the end of october. It all depends on the dates of my exams in university (which I currently don't know). Also, I'm not sure what's the most interesting to show people who don't know the project.

**Comment by GarkGarcia** [comment]
@rocky You may be interested in this too.

**Comment by rocky** [comment]
I can't commit time. I may be too busy with work. I nominate @mmatera  !!

**Comment by mmatera** [comment]
mmm, I am super busy too... And I do not have any experience with Sage...

**Comment by saraedum** [comment]
Thanks for replying. I think the talk could be very brief so the amount of preparation would also be quite minimal hopefully. I don't think you need to know anything about SageMath to talk at our SageDays. For us learning about what Mathics can and cannot do and where you would like to go would already be very valuable I think.

**Comment by rocky** [comment]
For the record, as I've said in the past I would like to see more interaction and cross development betwen the two projects. In particular I would like to seee a translator to Mathics to Python syntax calling Mathics libraries and in simple cases where these are not needed, there could be a translator to pure Python with sympy. 

I can't commit to anything, but if I have time I'll go over slides and at least mention this aspect.

**Comment by GarkGarcia** [comment]
> For us learning about what Mathics can and cannot do and where you would like to go would already be very valuable I think.

That's interesting. I think I could prepare a short talk about that (20 minutes at-most). @mmatera Would you be able to help me with that? The only issue I see is that I don't know what Sage is capable of and I imagine you guys wouldn't be that interested in stuff that Sage can do.

**Comment by mmatera** [comment]
@GarkGarcia : sure, but I do not have any idea about sage neither...

**Comment by saraedum** [comment]
> That's interesting. I think I could prepare a short talk about that (20 minutes at-most).

Sounds great.

> The only issue I see is that I don't know what Sage is capable of and I imagine you guys wouldn't be that interested in stuff that Sage can do.

Actually, I don't think that's the case. Even with very basic things, SageMath can at times be very lacking (slow, broken, ...) For example, I guess with things that you'd consider basic, it could be interesting to know where you see your strong and weak points as these are naturally the places where the people who like to build interfaces might want to have a look.

But even beyond that just saying hello so that the two communities know about each other is really valuable I think. I at least had never heard about Mathics until a few weeks ago.

**Comment by GarkGarcia** [comment]
> Actually, I don't think that's the case. Even with very basic things, SageMath can at times be very lacking (slow, broken, ...) For example, I guess with things that you'd consider basic, it could be interesting to know where you see your strong and weak points as these are naturally the places where the people who like to build interfaces might want to have a look.
> 
> But even beyond that, just saying hello so that the two communities know about each other is really valuable I think. I at least had never heard about Mathics until a few weeks ago.

Cool! I'll discuss this with @mmatera in today's meeting. We can give you a definitive answer after that.

**Comment by GarkGarcia** [comment]
Okay, @mmatera and I agreed to prepare something for SageDays. I've watched some introductory videos on Sage to get a better understanding of what it is capable of doing (so that I can talk about the differences between Sage and Mathics). Here's my plan for the presentation (at the moment):

* Talk a little bit about what is Mathics.
* Talk a little bit about symbolic evaluation.
* Talk about how pattern matching works in Mathics and how it's an intuitive language for expressing function definitions (apparently Sage doesn't do pattern matching).

@saraedum @mmatera Please let me know what you guys think about this.

**Comment by rocky** [comment]
In the Mathics part, I'd mention after an introduction to Mathics, what is
in 1.1.0 over  1.0. What the weaknesses are and what the plans are for
addressing this.

I'd mention something to distinguish what makes Mathics different from
Mathematica.

 Here I'd suggest and suggest that we move toward hooking into more of the
community that wants to make their packages available, but not under the
Wolfram company control.  I've said I'd like to see better integration with
[PackageData](http://packagedata.net/).

This kind of stuff I feel is more pertinent to Mathic and symbolic
evaluation which is done by several CAS systems. And in truth Mathics just
tries to do what Mathematica does, and I am sure there are tutorials on
Mathematica and its symbolic evaluation.

**Comment by mmatera** [comment]
@rocky  @GarkGarcia : Here I have started a CODIMD presentation 
 
https://demo.codimd.org/3IcktsBeRP-vFWinA84LJw?both

**Comment by GarkGarcia** [comment]
> In the Mathics part, I'd mention after an introduction to Mathics, what is in 1.1.0 over 1.0. What the weaknesses are and what the plans are for addressing this. I'd mention something to distinguish what makes Mathics different from Mathematica. Here I'd suggest and suggest that we move toward hooking into more of the community that wants to make their packages available, but not under the Wolfram company control. I've said I'd like to see better integration with PackageData - http://packagedata.net/ This kind of stuff I feel is more pertinent to Mathics and symbolic evaluation which is done by several CAS systems. And in truth Mathics just tries to do what Mathematica does, and I am sure there are tutorials on Mathematica and its symbolic evaluation.

Sure, that sounds interesting too. I'd like to at-least mention symbolic evaluation and pattern matching, but after that we can talk about where we are right now and what are our plans for the future. Sounds okay for you guys?

**Comment by GarkGarcia** [comment]
> @rocky @GarkGarcia : Here I have started a CODIMD presentation
> 
> https://demo.codimd.org/3IcktsBeRP-vFWinA84LJw?both

I'll try working on it this weekend, I'm quite busy at the moment 😅️

**Comment by rocky** [comment]
No problem. Thanks for the heads up. Not sure how much work I'll be able to do either, and the doc system is quite annoying in it monolithicness. (However if you put up with it, the results are good.)

**Comment by GarkGarcia** [comment]
@saraedum Are we scheduled yet? When you the presentation be?

**Comment by saraedum** [comment]
@GarkGarcia we have not completed the schedule yet. Since we'll run for 48 hours or so, do you have a preference about the time slot?

**Comment by GarkGarcia** [comment]
> @GarkGarcia we have not completed the schedule yet. Since we'll run for 48 hours or so, do you have a preference about the time slot?

I'll discuss this in our meeting and I'll have an answer to you by tomorrow.

**Comment by rocky** [comment]
There is a meeting?

**Comment by GarkGarcia** [comment]
> There is a meeting?

Lol, I assumed so... There's a couple things I'd like to discuss with you and @mmatera, it won't be long.

**Comment by rocky** [comment]
@saraedum  We talked over ideas for this talk and I may do the presentation. 

The catch though is that due to work constraints I can't present until after 16:30 UTC (12:30 EDT = UTC-4).
Is that okay? 

The current plan is to describe: 

* where we are at - we may have a release candidate ready
* what we can offer over Mathematica
* interactions with various open-source projects (sympy, sagemath, mathplotlib, Jupyter), ...

and last but not least ask for additional contributors...

**Comment by saraedum** [comment]
So 19:00 UTC on the 30th would work for you?

> The current plan is to describe: [...]

Sounds very good to me.

**Comment by rocky** [comment]
19:00 UTC is great - thanks.  Some combination or all of us might present.

**Comment by saraedum** [comment]
Hm...so what would be the names that we should put on our list of confirmed speakers? (It doesn't really matter if in the end another combination of people present.)

**Comment by rocky** [comment]
Gark Garcia @GarkGarcia 
Mauricio Matera @mmatera 
Rocky Bernstein

And if I have this wrong I am hoping the others will correct me.

**Comment by GarkGarcia** [comment]
@saraedum I have some questions about how will the presentation work. Is it going to be a livestream? If so, is there a link I can share with my friends and family for them to watch it? On which platform will the presentation be hosted?

@rocky @mmatera We should probably meet 10 minutes before the presentation to get everything set-up too (if you guys are available at that time).

**Comment by saraedum** [comment]
@GarkGarcia Unless you want to use another platform we provide Zoom or BBB for your talk. There's no live stream outside of these platforms but you can freely distribute the Zoom/BBB link. If you agree we will also record the talk.

**Comment by saraedum** [comment]
Do you have a title and an abstract for your talk so we can publish it on researchseminars.org?

**Comment by GarkGarcia** [comment]
> @GarkGarcia Unless you want to use another platform we provide Zoom or BBB for your talk. 

I think we'll go with BBB (@mmatera showed it to @rocky and I in our last meeting, but I didn't know the name of the tool). 

> There's no live stream outside of these platforms but you can freely distribute the Zoom/BBB link.

I see. Maybe I'll do a live stream in my personal PeerTube channel or something. In any case, are we responsible for creating the presentation link or will you guys take care of that?

> If you agree we will also record the talk.

Sure, it'd like it to be recorded. @rocky @mmatera how do you guys feel about that?

**Comment by GarkGarcia** [comment]
> Do you have a title and an abstract for your talk so we can publish it on researchseminars.org?

The title can be "Mathics: a free and open source alternative to Mathematica". I'm not sure what the abstract should be. @rocky @mmatera any ideas?

**Comment by saraedum** [comment]
> In any case, are we responsible for creating the presentation link or will you guys take care of that?

We'll take care of that.

Thanks for the title, it's now here: https://researchseminars.org/talk/SageDays110/23/

You might want to join https://zulip.sagemath.org/#narrow/stream/128-sd110 where we'll announce things during the conference. If you send me a private message on zulip, I can share the researchseminars credentials with you, so you can edit the abstract of the talk.

**Comment by mmatera** [comment]
> > Do you have a title and an abstract for your talk so we can publish it on researchseminars.org?
> 
> The title can be "Mathics: a free and open source alternative to Mathematica". I'm not sure what the abstract should be. @rocky @mmatera any ideas?

This could be a possible minimal abstract:

Mathics is an Open Source implementation of the Wolfram Language (https://en.wikipedia.org/wiki/Wolfram_Language), including a Python library,  a command-line interpreter, and a Django-based web interface. In this talk, we are going to present the status of the Mathics project, including some details of the recent release 1.1 and future perspectives.

**Comment by GarkGarcia** [comment]
> We'll take care of that.

Great! So, where can I find the link to the presentation? I'd like to share it with people I know beforehand.

**Comment by saraedum** [comment]
I sent you the link on zulip.

**Comment by saraedum** [comment]
People can also get the link to the BBB session at https://researchseminars.org/talk/SageDays110/23/ with instant registration now.

**Comment by GarkGarcia** [comment]
@saraedum Thank you very much for inviting us! I couldn't be happier with how the presentation turned out and I'm sorry I had to leave before the discussion with Miguel was over. Was the presentation recorded? If so, how can I access it?

**Comment by saraedum** [comment]
The recording is here: https://bbb.imo.universite-paris-saclay.fr/playback/presentation/2.0/playback.html?meetingId=13f0752852b2cf7dc1e08f807f73590c9a3f650d-1604079987388

Unfortunately, it's not separate from the previous talk so your part starts at 16:50. I'll try to turn it into two videos tomorrow.

**Comment by rocky** [comment]
Cool - this gives me an opportunity to find out the stuff before that I missed!

**Comment by GarkGarcia** [comment]
> The recording is here: https://bbb.imo.universite-paris-saclay.fr/playback/presentation/2.0/playback.html?meetingId=13f0752852b2cf7dc1e08f807f73590c9a3f650d-1604079987388

Thanks! Is there a way I can get this recording in a video format (something like mp4)?

> Unfortunately, it's not separate from the previous talk so your part starts at 16:50. I'll try to turn it into two videos tomorrow.

No problem, I can edit it myself when I have the video files 😁️

**Comment by saraedum** [comment]
I think the video files are https://bbb.imo.universite-paris-saclay.fr/presentation/13f0752852b2cf7dc1e08f807f73590c9a3f650d-1604079987388/deskshare/deskshare.webm for the presentation and https://bbb.imo.universite-paris-saclay.fr/presentation/13f0752852b2cf7dc1e08f807f73590c9a3f650d-1604079987388/video/webcams.webm for the camera video.

If you could turn these into two videos that would be great (I have no idea how to do that.)

**Comment by GarkGarcia** [comment]
@mathics/maintainers @saraedum I'm hosting the video of the talk in my personal-website at https://pablo.escobar.life/2020/11/19/mathics-presentation.html
