### ISSUE TITLE
Docker tasks.

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#927]
I've created a docker container at https://hub.docker.com/repository/docker/rockyb/mathics for fairly recent 1.1-dev sources. 

However there are a number of loose ends that need to be worked out. 

* <strike>This should be under the mathics organization, but I have no idea who has access to that. The mathics organization doesn't seem to have released any public docker images.</strike>
* The docker image should be updated automatically on each master commit. This can also be done in conjunction with testing the image after it is built.
* This image fails to build the pymathics `natlang` module. The siituation here is that I think it should remain broken until a separate repostiory for `natlang` is setup and then this will build from that rather than have try to do it from the Mathics/mathics repostority

I've alerted the author about recent activity and the new docker containers. Perhaps he'll be interested in putting his repository in the Mathics organization.

**Comment by GarkGarcia** [comment]
> * This should be under the mathics organization, but I have no idea who has access to that. The mathics organization doesn't seem to have released any public docker images.

I think @poeschko can help with that.

> * The docker image should be updated on each master commit.

There may be a way to do that with GitHub Actions (?)

> * This image fails to build the pymathics natlang module. The siituation here is that I think it should remain broken until a separate repostiory for natlang is setup and then this will build from that rather than have try to do it from the Mathics/mathics repostority

Makes sense.

**Comment by poeschko** [comment]
Unfortunately I don't own the mathics organization on docker and I don't know who does.

In the meanwhile, I created https://hub.docker.com/orgs/mathicsorg so we could use that. Let me know who wants to join as a member.

**Comment by rocky** [comment]
My id is rocky and if I join as a member, I'll push there and remove the other docker container.

(Someone else I hope will update the README.rst)

**Comment by rocky** [comment]
Ooops. my id is *rockyb* . It has been corrected above.

**Comment by rocky** [comment]
With respect to the `natlang` failure to build. I think we should remove that from Mathics. I spoke to @mmatera  about this the other day. It is wrong. Whe a pymathics module is loaded, additional steps need to be done to add it to the namespace. 

The current code where it is assumed that there are pymathics modules that are built in was transitional or a stepping stone for starting to pull apart Mathics. 

Note that natlang too pulls in some hefty OS dependencies. That too is why in my opinion it shoudl be in its own repo and have its own release cycle.

**Comment by rocky** [comment]
I should note that the other way where there is one repo with separate PyPI installable packages is another way folks organize things. I am not particularly in favor of that, but it is another approach.

**Comment by slel** [comment]
> I don't own the mathics organization on docker and I don't know who does.

Maybe @sn6uv? Or @sealemar?

> In the meanwhile, I created https://hub.docker.com/orgs/mathicsorg
> so we could use that. Let me know who wants to join as a member.

**Comment by rocky** [comment]
The weird thing is that neither have used it to create a docker image.

**Comment by rocky** [comment]
Docker images are now handled in the [mathics-omnibus project](https://github.com/Mathics3/mathics-omnibus)
