### ISSUE TITLE
Add "computer-algebra" github-topic to mathics/Mathics repo on GitHub

### ISSUE THREAD

**Issue by slel** [mathics/Mathics#935]
Make Mathics appear in the "computer-algebra" topics list at:

- https://github.com/topics/computer-algebra

by adding the "computer-algebra" github-topic to
the mathics/Mathics repo on GitHub.

**Comment by rocky** [comment]
I think that is done now. If so, close the issue.

**Comment by slel** [comment]
Thanks!
