### ISSUE TITLE
Revise the documentation

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#945]
@rocky and I plan to go over the PDF documentation to make sure everything is up to date before 1.1.

**Comment by rocky** [comment]
Fantastic. One thing I am working on though is a way to tag examples in the doc. And when that's done more examples will be added. 

So the ugly formatting of examples in say `Environment` just leave.

In conjunction with this I'll probably add a `--count` parameter to `test.py` to reduce the amount of time needed to test such doc changes.

**Comment by mmatera** [comment]
How does this new parameter would work? just testing the first n tests?

Regarding splitting tests and examples, the current version has a mechanism implemented:

(From the Doctest class definition docstring)
"""
DocTests formating rules:

     #> signifies private test that does not appear as part of the documentation
    X> outputs the docs as normal, but the test is not run
    = compares the result text
    : compares an (error) Message
    | signifies Print output
""

**Comment by rocky** [comment]
> How does this new parameter would work? just testing the first n tests?

I gave this some thought. The idea is that it would be used with `--skip` or `--section`.  There is already a `--stop-on-faiure`.  

But suppose I just want to run the last test that failed and not run to the end of the test suite. Here a count is the most useful thing. For example, it might be 1. If  you know there are a couple of tests in the suite, it might be that number. Giving an absolute value is more cumbersome. 

> DocTests formating rules:

This is useful. I wasn't aware of `X>` and more more use of it. And the others. Is this described somewhere? I don't see it in the wiki for example.

**Comment by GarkGarcia** [comment]
@rocky Unfortunately I wont be able to work on this until the weekend, but I can take care of that in the weekend and we can release 1.1 in the following week.

**Comment by GarkGarcia** [comment]
@rocky I went over the docs for the bultins I've added and I think we're good. However, in the process of reviewing the docs I found a bug in the Django interface. You report it properly in a minute.

**Comment by mmatera** [comment]
Is something else pending on this issue, or can be closed?

**Comment by rocky** [comment]
Just posted stuff to maintainers about this. Whether you want to keep this open or closed is up to you all. I care about getting documentation in shape.
