### ISSUE TITLE
Allow building web documentation without running tests

### ISSUE THREAD

**Issue by suhr** [mathics/Mathics#947]
Tests take quite a long time to run. It is ok for CI, but overall is not always desirable.

**Comment by rocky** [comment]
This is a post 1.1 item. See https://github.com/mathics/Mathics/pull/948 for example.

**Comment by rocky** [comment]
Change that. This was so annoying in trying to update the documentation (for 1.1) that it was expedient to add a `--doc-only` flag.

The Facisit regime of making all tests, passing all tests, and _only_ then allow document production made more sense in an era before CI and different CI workflows, and when there were fewer tests.
