### ISSUE TITLE
Symbolic Min/Max

### ISSUE THREAD

**Issue by weakit** [mathics/Mathics#956]
`Min[E, Pi]` currently does not give a result.

This is what Wolfram gives:

![image](https://user-images.githubusercontent.com/34541656/95680935-b5842d00-0bfa-11eb-92f3-4a9700955d21.png)

`sympy` has inbuilt Min/Max functions that have the same functionality:

```python
>>> Min(E, pi)
E
```

One thing to note tho is that `sympy`'s min/max is pretty slow with large (>1000 element) lists. See sympy/sympy#16249.

**Comment by rocky** [comment]
You can find  classes `Min`, `Max` and the internal class used `_MinMax` [here](https://github.com/mathics/Mathics/blob/master/mathics/builtin/comparison.py#L686-L787).

Although crude, all I did was run `grep -r 'class Min('` from the top-level directory. 

If you can fix and put in a PR that'd be awesome.

**Comment by weakit** [comment]
It was stupid, but since at the time I didn't have the source code, I tried searching through the code on GitHub. Searching for Min or Max didn't give me a good hit.

GitHub search isn't reliable I guess.

I'll see what I can do.

**Comment by mmatera** [comment]
Implemented at PR #982
