### ISSUE TITLE
The Django interface fails to run the examples in the documentation

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#958]
This is a follow up to https://github.com/mathics/Mathics/issues/945#issuecomment-706735449. Here's the bug:

![Screenshot from 2020-10-11 14-17-36](https://user-images.githubusercontent.com/37553739/95685180-ac7c6700-0bcc-11eb-8b49-2246dc22764e.png)

The issue is that when the user presses the `=` button in the documentation tab to evaluate an example somewhow the example get's HTML-escaped (the spaces are replaced with `&nbsp;`). This is a bug.

I'd like to get this fixed before the 1.1 if it's possible.

**Comment by GarkGarcia** [comment]
I'm not able to find the source of the bug, since I don't really know how the web interface works internally.

**Comment by suhr** [comment]
```
function showPage(response) {
	if ($('doc')) {
		$('doc').updateDOM(response.content);
	}

    $$('li.test p').each(function(test){
        test.insert($E('span',
                    {'class': 'submitbutton', 'title': "Run this example!"},
					submitButton = $E('span', $T('='))
				));

        test.observe('mouseover', function(e){
            $(test).addClassName('focused');
        });
        test.observe('mouseout', function(e){
            $(test).removeClassName('focused');
        });

        $(test).descendants()[1].observe('click', function(){
            var query = $(test).descendants()[0].innerHTML;
            query = query.replace(/\xA0/g, ' ');
            query = query.unescapeHTML();
            setQueries([query]);
        });
    });

	$$('ul.test').each(function(test) {
		var id = test.id.substr(5); // 'test_...'
		var data = response.data[id];
		setResult(test, data.results);
	});
}
```

On a button click, it gets a formatted query and tries to unescape it. The problem is, the `unescapeHTML` function is inadequate:

```
  function unescapeHTML() {
    return this.stripTags().replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&');
  }
```

**Comment by suhr** [comment]
Some day we should replace all that mess with something better. But for now, adding `.replace(/&nbsp;/g,' ')` will do.

**Comment by GarkGarcia** [comment]
> The problem is, the `unescapeHTML` function is inadequate:

Ohh I see. Isn't there a standard function for doing this in JS?

**Comment by GarkGarcia** [comment]
> Some day we should replace all that mess with something better. But for now, adding `.replace(/&nbsp;/g,' ')` will do.

Makes sense. I'll try to find an appropriate solution for this. If I can't find it I'll add `.replace(/&nbsp;/g,' ')` as you suggested.

**Comment by suhr** [comment]
Is seems like there isn't, which makes no sense, but it's, you know, JavaScript. Anyway, we should not extract code from the text, instead we should allow getting the examples content by the hash with ajax request.

**Comment by GarkGarcia** [comment]
> Anyway, we should not extract code from the text, instead we should allow getting the examples content by the hash with ajax request.

Makes sense. We could store the hashed expression in the `data` attribute or something. Could you give it a try?

**Comment by GarkGarcia** [comment]
> We could store the hashed expression in the `data` attribute or something.

We don't even have to hash it, we could just store it's string representation in the button's `data` attribute when generating the page from the Django side.

**Comment by suhr** [comment]
> Could you give it a try?

Will probably do, but later. For now, let's just use `.replace(/&nbsp;/g,' ')`.

**Comment by GarkGarcia** [comment]
> > Could you give it a try?
> 
> Will probably do, but later. For now, let's just use `.replace(/&nbsp;/g,' ')`.

Ok. I'll patch this as you suggested but I'll create a separate issue for this so that we don't forget about it.
