### ISSUE TITLE
Bug in Table when substituting a list for an iterator

### ISSUE THREAD

**Issue by rebcabin** [mathics/Mathics#960]
(this one is blocking my upcoming PR with many tests in symbolic logic)

Kindly consider the following small, self-contained repro case, which works in Mathematica:

```
ClearAll[tc, or, fn, a, b, t, f]

binaryFunctionList = {tc, or}

binaryTruthTableBugged =
    Table[fn[a, b],
        {fn, binaryFunctionList},
        {a, {t, f}}, {b, {t, f}}]

binaryTruthTableNoBug =
    Table[fn[a, b],
        {fn, {tc, or}},
        {a, {t, f}}, {b, {t, f}}]
```

In mathics, after a fresh start, it produces:

```
Quit[]
In[1]:= <<"GS2bug2.m"
Table::iterb: Iterator does not have appropriate bounds.
Out[1]= {{{tc[t, t], tc[t, f]}, {tc[f, t], tc[f, f]}}, {{or[t, t], or[t, f]}, {or[f, t], or[f, f]}}}

In[2]:= 
```

**Comment by rocky** [comment]
I'll take a look at this when I have a chance. 

Something I've been meaning to ask of those who know Mathematical better than I: if something like this happened in Mathematica, what would you typically use to track down what's going wrong?

**Comment by mmatera** [comment]
Table[F[x],{x,{a,b,c,d}]] 
returns in wma {F[a],F[b],F[c],F[d]}

I will try to implement this.

**Comment by mmatera** [comment]
Already solved (I think). Please have a look at PR #963

**Comment by rocky** [comment]
@rebcabin ... and if this addresses the issue please close.
