### ISSUE TITLE
Wrong behavior of  StringSplit with WhitespaceCharacter

### ISSUE THREAD

**Issue by rocky** [mathics/Mathics#969]
```StringSplit["13  a22    bbb", WhitespaceCharacter] // InputForm```
should be: 
```
{"13", "", "a22", "", "", "", "", "bbb"}
```

**Comment by mmatera** [comment]
why? It seems to be just one blank space in the original string.

**Comment by GarkGarcia** [comment]
> why? It seems to be just one blank space in the original string.

I don't understand what the issue is too.

**Comment by rocky** [comment]
after `a22` there are 3 spaces. See https://reference.wolfram.com/language/ref/WhitespaceCharacter.html?q=WhitespaceCharacter
