### ISSUE TITLE
The docs are broken again

### ISSUE THREAD

**Issue by GarkGarcia** [mathics/Mathics#978]
See https://travis-ci.org/github/mathics/Mathics/jobs/736336902#L22900. Someone replaced `xelatex` with `pdflatex`, which does not work for us as established before.

**Comment by GarkGarcia** [comment]
It looks like the docs were broken in https://github.com/mathics/Mathics/commit/3b1de924957ed1f97e62457b8687bffdc067f801.

**Comment by mmatera** [comment]
Seems to be fixed now. What could be pending is to add good tests for MathMLForm in the pytest engine.

**Comment by GarkGarcia** [comment]
> Seems to be fixed now. What could be pending is to add good tests for MathMLForm in the pytest engine.

Indeed! I think @rocky fixed it in the last commit.
