### ISSUE TITLE
Consider MIT, Apache, or BSD license for core modules?

### ISSUE THREAD

**Issue by rebcabin** [mathics/Mathics#997]
My use cases are all about calling mathics from other Python code, that is, using mathics as a module library that just does calculations, not for plotting, rendering, the web interface, django, etc. For this use case, my clients don't want to be forced to distribute their calling code under GPL v3.

MIT, Apache, BSD and (probably) some others seem (to my inexpert, non-legal eye) all more friendly: the module library stays open-source, but the calling code isn't forced to open-source.

Perhaps the core libraries of mathics could be re-licensed under MIT, Apache, BSD, etc.

EDIT:
Concretely I use the following (and that's everything I need from mathics for this client's use case). They are concerned that code that imports these modules from mathics could be forced into open-source distribution.

```
from mathics.core.parser import \
    parse as mathics_parse, \
    SingleLineFeeder
from mathics.core.definitions import Definitions
from mathics.core.evaluation import Evaluation
```

**Comment by suhr** [comment]
Possible, but changing a license (AFAIK) requires an agreement from all contributors.

**Comment by mmatera** [comment]
I guess it would be possible. Maybe we could do a survey asking the contributors for their positions.

**Comment by rebcabin** [comment]
Thanks much for at least considering it :+1:

**Comment by GarkGarcia** [comment]
I'm not sure if GPLv3 allows re-licensing, I'll look into it.
